### ISSUE TITLE
JNDI rebind doesn't work on Open Liberty

### ISSUE THREAD

**Issue by Thihup** [javamelody/javamelody#1023]
Hi. I'm trying Javamelody with Open Liberty and for the most part it works just fine.
However, it cannot monitor the SQLs and JDBC connections because it seems that Open Liberty doesn't support JNDI rebind.

In the log I get:
```
Thu Jun 10 10:14:19 BRT 2021     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/foo]
Thu Jun 10 10:14:19 BRT 2021     DEBUG     rebinding datasource java:comp/env/jdbc/foo failed, skipping it
```

To work around it, I've tried to use the `net.bull.javamelody.JdbcDriver` driver, however, Open Liberty doesn't allow put JDBC drivers in the WEB-INF/lib :|

 I had an idea, but I don't know if it would be possible: Create a new jar with only the classes for the JdbcDriver, so I could put it in the global classloader and the Javamelody jar in the WEB-INF/lib.

**Comment by evernat** [comment]
Hi, I doubt that adding a driver in the global classloader is a solution, because it probably won't talk easily to classes from WEB-INF/lib. But you can try if you want.

The support of jdbc and sql monitoring in Open Liberty is not a high priority at the moment. (Not many users of javamelody in Open Liberty as far as I know.)
Anyway, it may work for you if the datasource from JNDI is "rewrapped" instead of "rebinded".
By "rewrapped", I mean something like that in the JdbcWrapper#rewrapDataSource method, when using Liberty Profile (see [initial patch](https://github.com/javamelody/javamelody/files/1497768/issue411_v0.1.txt) which some remarks):
```java
} else if (websphereLibertyProfile
		&& connection.getClass().getName().contains("WSJdbcConnection")) {
	final String conFieldName = "connImpl";
	Connection con = (Connection) JdbcWrapperHelper.getFieldValue(connection, conFieldName);
	// on teste isProxyAlready ici pour raison de perf
	if (!isProxyAlready(con)) {
		con = createConnectionProxy(con);
		JdbcWrapperHelper.setFieldValue(connection, conFieldName, con);
	}
}
```

**Comment by Thihup** [comment]
I'll give it a try

**Comment by evernat** [comment]
ok, let us know if it works.
