### ISSUE TITLE
Javamelody Security question , compatibility with LDAP

### ISSUE THREAD

**Issue by SiddGhoshGit** [javamelody/javamelody#1029]
Hello Team,

I would like confirm is javamelody built to support LDAP ? I mean integrating javamelody with LDAP and use it credentials for authentication on login page? ,

 If yes , is there any documentation available for integrating javamelody with LDAP?

or
the following is the only login mechanism available ?
https://github.com/javamelody/javamelody/wiki/UserGuide#16-security , using web.xml and credentials stored inside tomcat-users.xml.

Please advise.

**Comment by evernat** [comment]
The /monitoring page of javamelody does not have integration for LDAP itself. But that's just an URL in webapp, you can secure that URL as you wish like other URLs in your webapp.

If you want to secure the /monitoring page, yes you can look at https://github.com/javamelody/javamelody/wiki/UserGuide#16-security. If you don't want to use the allowed-addr-pattern or authorized-users parameters, yes you can use web.xml and credentials inside the container: that's the standard JavaEE / JakartaEE way. For Tomcat, you may list users in conf/tomcat-users.xml or if you want to use LDAP for a users' realm instead of a memory realm from conf/tomcat-users.xml, then look at the Tomcat's doc for a realm from LDAP: https://tomcat.apache.org/tomcat-9.0-doc/realm-howto.html#JNDIRealm

Or you can certainly do that with Spring-security if your webapp uses Spring. My own work is for webapps using Spring-boot and SAML with SSO/LDAP including for the /monitoring URL.
