### ISSUE TITLE
Dependency Information

### ISSUE THREAD

**Issue by KanagarajGanapathy** [javamelody/javamelody#1034]
Hello Team,

In Newer versions of java melody, we could not see the dependencies [JARS] information.. Previous information could able to see the all jars used .. 

Please see the attachment for the reference.

Please help us to see the JARs details in newer version.
Version :1.85 [no information about Jars]
![image](https://user-images.githubusercontent.com/18610422/130732021-d93ee96f-5a34-4497-a92d-f5beafeacb7c.png)
Version 1:65 : [Information available]
![image](https://user-images.githubusercontent.com/18610422/130732060-5e7ce851-cc25-43c5-95f1-6ef49ae0a87b.png)

**Comment by evernat** [comment]
Is your webapp the same in the same version in the two cases? And do you see the jar dependencies if you put javamelody 1.65 instead of javamelody 1.85 in your current webapp temporarily?

**Comment by evernat** [comment]
It is a spring boot application. And javamelody has never displayed the dependencies of a spring boot application, when launched as a jar file with spring-boot:run or with java -jar. The dependencies are displayed in the monitoring page for a webapp packaged as war file, for example when the spring boot app is packaged as war file.

At the moment, if I put the 1.65.0 version of javamelody into the pom.xml of the sample project, it does not display dependencies like you said, And in fact, the monitoring page is not displayed at all in this case, probably because the 1.65.0 version of javamelody was for spring boot v1 and the sample is using spring boot v2.

By the way, you should probably upgrade javamelody to 1.88.0.

Is it clear for you?

**Comment by KanagarajGanapathy** [comment]
> It is a spring boot application. And javamelody has never displayed the dependencies of a spring boot application packaged as a jar file and launched with spring-boot:run or with java -jar. The dependencies are displayed in the monitoring page for a webapp packaged as war file, for example when the spring boot app is packaged as war file.
> 
> At the moment, if I put the 1.65.0 version of javamelody into the pom.xml of the sample project, it does not display dependencies like you said, And in fact, the monitoring page is not displayed at all in this case, probably because the 1.65.0 version of javamelody was for spring boot v1 and the sample is using spring boot v2.
> 
> By the way, you should probably upgrade javamelody to 1.88.0.
> 
> Is it clear for you?

yes, it is clear....Thank you for the answers....
Have a nice day.
