### ISSUE TITLE
Disbale / Hide informations

### ISSUE THREAD

**Issue by KanagarajGanapathy** [javamelody/javamelody#1043]
Hello Team

Is there any way to hide/ disable JVM arguments in java melody page? 

1. Either hiding JVM arguments
2. Hiding System information completely
3. Hiding Details button under System information.

If we could able to do at least one it will be really helpful for us.

**Comment by evernat** [comment]
Sorry, there is no way to do that.
I recommend to never put confidential data in the command line of the process, because it would be displayed in the list of process of the OS (ps command in Linux or tasklist in Windows) or in commands history for example.

Instead, you can put confidential data in environment variables,
or if you use Tomcat, in [catalina.properties](https://tomcat.apache.org/tomcat-9.0-doc/config/index.html) which lists system properties like in the command line,
or if you still use Tomcat, as [context parameters](https://tomcat.apache.org/tomcat-9.0-doc/config/context.html#Context_Parameters) in the xml file of the context of your webapp,
or in a specific configuration file available to your webapp,
or anyway except in the command line.
If you absolutely need system properties without using catalina.properties, you can set them in code based on another configuration.
