### ISSUE TITLE
Export all metrics to prometheus

### ISSUE THREAD

**Issue by exxbrain** [javamelody/javamelody#1050]
Hello, 

Please add all metrics that are containing in pdf to prometheus I mean metrics for database queries, http requests metrics and so on. It would be helpful. Please explain if it is not possible.

**Comment by evernat** [comment]
For http requests, there are already hits count, errors count and duration millis, which are totals for all http requests. And the mean duration of all http requests is duration millis / hits count.
And this is the same for sql requests and others, among others javamelody metrics for Prometheus.
Do you want more values than that?

Perhaps you want the hits count, errors count and duration millis for whatever select from table A, and the same for insert into table A and for update table A and for delete from table A.
And the same for each sql request in your webapp.
For most applications, it would mean many thousands of values (possibly 100000 values) every 60 seconds. I think that it's not reasonable, for the Prometheus server and for the overhead on the application.
Is it ok for you?

**Comment by evernat** [comment]
no response from the reporter

**Comment by myhellone** [comment]
Hi!

Is there any method to export all metrics from JavaMelody to Prometeush?

I would like exactly the same as the author of this isse, I am aware of the consequences, but due to the fact that our environment is growing and we are going to lose all metrics in Prometeush / Victoria Metrics and present the data in Graphana.
