### ISSUE TITLE
With a collect server how to pass an url parameter on the instance url ?

### ISSUE THREAD

**Issue by ricetrac** [javamelody/javamelody#1107]
Hi,

Our application is deployed with several tomcat instances, and the distribution of user calls is done via an Apache Frontend.
Access to a specific instance can be done by indicating a "jsessionid" parameter in the url.
Example: https://gaprod/application?.jsessionid=instance1

But when adding an application with several instances in Javamelody, the collector systematically applies the suffix "/monitoring?collector=stop&format=serialized" after the url set for each instance, which gives for example with my previous url :
"https://gaprod/application?.jsessionid=instance1/monitoring?collector=stop&format=serialized"

So the instance information is completely lost, and javamelody does not collect information from all instances.

Would it be possible to configure the collector so that it does not modify the url of the instance provided?
And so we could directly configure the final url of each instance.
Example: "https://gaprod/application/monitoring?.jsessionid=instance1&collector=stop&format=serialized
, https://gaprod/application/monitoring?.jsessionid=instance2&collector=stop&format=serialized"

Thanks

**Comment by evernat** [comment]
It seems strange to use a query parameter instead of a header for that and it seems even more strange to me to name it jsessionid which has a special meaning for http sessions (not proxy route) : https://docs.oracle.com/javaee/6/api/javax/servlet/SessionCookieConfig.html#getName()
It would seem less ambiguous to use a name like a ROUTEID.

That said, yes, when using a collector server, it could behave to cut and past the query parameters given by the user at the end of that url.

**Comment by ricetrac** [comment]
Hi evernat,

Thank You for this fix.
