### ISSUE TITLE
JavaMelody to Prometheus

### ISSUE THREAD

**Issue by myhellone** [javamelody/javamelody#1118]
Hi!

Is there any method to export all metrics from JavaMelody to Prometeush?

I am aware of the consequences, but due to the fact that our environment is growing and we are going to lose all metrics in Prometeush / Victoria Metrics and present the data in Graphana.

**Comment by myhellone** [comment]
...

**Comment by evernat** [comment]
hello @myhellone 
Sorry for the delay.

I suppose that you have already configured Prometheus to scrape javamelody metrics as said at
https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#exposing-metrics-to-prometheus

If you speak about backfilling past data, I do not know a method to export all metrics from JavaMelody to Prometheus. If possible, it may not give what you want, since values in javamelody graphics are aggregated more and more over time. So after some time, those values are not as detailed as you may want in javamelody storage (that is in *.rrd files which are round robin data), at least compared to values exported to Prometheus minute by minute.

Or if you speak about exporting more metrics from javamelody graphics to Prometheus, see about includeLastValue in javamelody doc for Prometheus:
https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#exposing-metrics-to-prometheus
