### ISSUE TITLE
The menu item doesn't work!

### ISSUE THREAD

**Issue by robozb** [javamelody/javamelody#1134]
![Képkivágás](https://user-images.githubusercontent.com/8656998/206969286-c48a7223-77d3-4ac9-8d5d-68a7837b1bb0.JPG)

**Comment by evernat** [comment]
About the issue: I suppose that something has changed in github, about the "Wiki" link at the top ending like "/wiki" instead of "/wiki/" for the home page. And so the sidebar relative links did not work on the home page whereas the relative links worked from other wiki pages.

I fixed the issue by using an undocumented or unbroken syntax `[[Link Text|nameofwikipage]]` a bit like Mediawiki syntax at https://docs.github.com/en/communities/documenting-your-project-with-wikis/editing-wiki-content#adding-links. (Markdown is supposed to use full url, while I really prefer to use nameofwikipage).
And so links works from both home wiki page and from other pages.

**Comment by evernat** [comment]
and thanks for the issue !

**Comment by robozb** [comment]
Thanks for the quick reply!
https://github.com/javamelody/javamelody/wiki/UserGuide
