### ISSUE TITLE
Support for JBoss 4.0.2

### ISSUE THREAD

**Issue by paulwuethrich** [javamelody/javamelody#1145]
Embarrassed to ask...it's a long story but...

Anyone get this project to work with JBoss 4.0.2/4.0.x?

**Comment by evernat** [comment]
In theory and by incredible chance, javamelody still supports servlet api 2.4, which is needed for JBoss 4.0.x.

But I am not sure that many have tested javamelody on JBoss 4.0.x, 15 years ago. Even me, I am not sure if have tested javamelody in JBoss with 4.2 or 5.0 first. And so I would have better luck on lottery than still have compatibility with JBoss 4.0.x 15 years later.
I think that there is almost no chance that a JBoss 4.0.x user walks here, even with Google (those users have migrated or are retired now ;-)).

Since there is no error, no bug, no issue here, I close this. You may have better luck with stackoverflow in my opinion.
Good luck.
