### ISSUE TITLE
Bad count of hits of agregated two tomcat

### ISSUE THREAD

**Issue by tomaszmacnar** [javamelody/javamelody#1152]
JavaMelody version: 1.90.0
I have statistic of two application: tomcat_1 and tomcat_2

And 3rd i want to have summary of tomcat_1 and tomcat_2 (application.properties):
tomcat_all=tomcat_1, tomcat_2

In tomcat_all application (spring statistics) i have wrong numer of hits of one method (the numer is much bigger then in sum tomcat_1 and tomcat_2). 

Any sugestions ? What could be wrong ?

**Comment by evernat** [comment]
In the optional collector server, this could happen sometimes when adding an aggregation from other monitored apps. A workaround would be to restart the server.

This should be fixed by f4d8ac4. A snapshot build is available at
http://javamelody.org/downloads/javamelody-collector-server-1.99.1-SNAPSHOT.war

I have also fixed the actions (run the garbage collector, invalidate http sessions, ...) in the aggregation at the same time.
