### ISSUE TITLE
Reset values not working

### ISSUE THREAD

**Issue by vittetan** [javamelody/javamelody#1156]
Hi, 

Firts of all, thank you for your great tool, it's amazing how much we can dive into our own code and see the different problems.

Now my problem:
I'm using javaMelody (1.94.0) with my springboot app, and when I want to reset the different values, it only reset the values on the "all" period, and it doesn't erase anything in others periods.

**Comment by evernat** [comment]
It's a feature, because you can't erase the past.
After some days, that past will not be much visible. So you may just wait.
If you want to have a clean room to just monitor some requests or some minutes, choose the "all" period and reset as you wish like you have already done.

Or if you really want to erase all, you can stop the app then you can delete all rrd and ser.gz files in the storage directory (in the tmp directory by default) and restart the app.
