### ISSUE TITLE
Hazelcast Issue

### ISSUE THREAD

**Issue by matrenner** [javamelody/javamelody#1160]
I have an application that uses hazelcast and whenever i try to visit the javamelody monitoring page it causes hazelcast to try and connect to the default cluster. How do i prevent this? I've tried many different settings from the hazelcast side, but none seem to be working.

**Comment by tomekkup** [comment]
Got same issue. It occurs only on Payara 5

**Comment by evernat** [comment]
As said for Ignite thin client in #962, Hazelcast declares itself as a JSR107 CachingProvider in META-INF [here](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/META-INF/services/javax.cache.spi.CachingProvider), which is implemented [here](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/cache/HazelcastCachingProvider.java).

javamelody gets the JSR107 CachingProviders, if available, to discover names and statistics of caches. That's [here](https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/internal/model/JCacheInformations.java#L94).

When `javax.cache.spi.Caching.getCachingProviders()` and `cachingProvider.getCacheManager()` is called, Hazelcast seems to try and connect the default cluster as you said.
But you expect that Hazelcast does not do that.

In my opinion, javamelody and any code should be able to get the list of available JSR107 CachingProviders anytime. And Hazelcast is not supposed to do something as connecting to a cluster which you have not configured it for, even if a discovering api such as `javax.cache.spi.Caching.getCachingProviders()` is called. If you don't want Hazelcast to connect to a default cluster, there should be a way in Hazelcast to disable that default cluster.

Otherwise as a workaround, javamelody calls `Caching.getCachingProvider()` only if the `javax.cache.Cache` class is available. So you may exclude the `javax.cache:cache-api` Maven dependency if it's possible in this case.
Or perhaps you can set `-Dhazelcast.jcache.provider.type=member` as system property to configure default behavior of Hazelcast.

Is one of these works for you?

**Comment by evernat** [comment]
See also https://github.com/payara/Payara/issues/5476 which could be created again based on calling `Caching.getCachingProvider()` and not with javamelody, since javamelody can't be compared with Payara monitoring console in my opinion unlike @MeroRai excuse for closing.

**Comment by tomekkup** [comment]
I'm working with Payara 5.2022 . Switching cacheprovider into member mode worked for me (I mean use of jvm parameter `-Dhazelcast.jcache.provider.type=member`)

**Comment by evernat** [comment]
So, closing this issue for the reasons given at https://github.com/javamelody/javamelody/issues/1160#issuecomment-1565656656
with the possible workaround of the system property `-Dhazelcast.jcache.provider.type=member` as jvm parameter.
