### ISSUE TITLE
Persist statistics data to database

### ISSUE THREAD

**Issue by nimelord** [javamelody/javamelody#1176]
Such possibility lets use your great functionality on systems with several nodes also on the k8s pods.
Anyway, thank you for your project!

**Comment by evernat** [comment]
Persisting statistics data to database is not planned because a priority is local and fast IO for most usages and no external dependency to keep it simple to install, so closing this issue.

That said, you can have external and even aggregated storage using the optional [collect server](https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#optional-centralization-server-setup), if you want.
