### ISSUE TITLE
MBeans view on JBoss/WildFly leads to OutOfMemoryError

### ISSUE THREAD

**Issue by liefke** [javamelody/javamelody#1180]
I'm using JavaMelody in an JBoss/WildFly application with about 60 JPA entities and run that server with 4 GB heap space (-Xmx4096m), which is usually enough - especially during development.

When opening the MBeans view (.../monitoring?part=mbeans), the server runs into an OutOfMemoryError. I therefore increased the heap space to 8GB, which prevents the error. But the whole HTML page takes up about 2.5 GB, which loads nearly forever (especially over slower networks) and is too much to display for some browsers.

I checked the content of the page and most of it seems to come from Infinispan, which generates a lot of MBeans for each entity (in my application there are overall ~6000 MBeans), many of them providing the whole configuration in an attribute named "configurationAsProperties", each ~250 KB when printed as string.

I created a JavaMelody patch which suppresses that attribute. As a result the HTML page has a size of 18 MB and is easy to use in each browser.

Another patch, which limits the formatted attribute values to 128 characters, has nearly the same impact on the page size, but takes a bit longer to process, because each 250 KB string is first generated and then truncated.

I suggest to integrate both options into JavaMelody:

Option 1) Truncate the attribute values to a configurable amount of characters, with a default value of something between 100 and 1000 (128 characters seems fine to me). As result even without any configuration the OutOfMemory won't occur.
Option 2) Add a configuration option to exclude specific attributes and MBeans from the view. This would speed up the MBean generation but would need fine tuning for each application.

I could provide a PR, if this helps to understand both options.

Another option would be to retrieve the values only when the MBean node is opened in the browser, but that would be a bigger modification of code compared to the other options.

**Comment by evernat** [comment]
Indeed. 
I read in https://infinispan.org/docs/stable/titles/hibernate/hibernate.html :
> Usually each entity hierarchy or collection has its own region 

or in https://docs.jboss.org/author/display/ISPN53/Using%20Infinispan%20as%20JPA-Hibernate%20Second%20Level%20Cache%20Provider.html :
> With the Infinispan cache provider, each entity/collection type gets each own cache instance

I choose option 3: always exclude the `configurationAsProperties` attribute, because some other users may have the same issue as you and the need to know the right configuration is not good. It is a bit sad for the few users who would be happy to see the configuration of infinispan caches (or other mbeans which have a `configurationAsProperties` attribute), but too much is too much for your case and we need to kill this issue.

**Comment by liefke** [comment]
@evernat: Now there are already two properties that are suppressed: "password" and "configurationAsProperties". 

Wouldn't it make sense to use these as default for a configuration option? I can imagine, that there are more sensitive properties, which some users would like to suppress.
