### ISSUE TITLE
Display virtual thread name and stack trace in the current requests (Java 21)

### ISSUE THREAD

**Issue by gshumakher** [javamelody/javamelody#1227]
Tomcat 10.1.10 and later added support for Java21 virtual threads via Connector attribute `useVirtualThreads="true" `.
Please add support for this configuration.
As of now the running request does not show nor current thread name nor stacktrace.

Thanks

**Comment by evernat** [comment]
javamelody already supports quite well virtual threads when configuring Tomcat or other for virtual threads using Java 21. There is no exception, including when displaying the monitoring page. The threads are displayed in the monitoring page as usual. The virtual threads probably can't be added with these platform threads in the monitoring page because there can be many thousands virtual threads.

As you said, the issue is that the name and stack trace of the virtual thread is not displayed in the current requests.

![virtual threads](https://github.com/user-attachments/assets/1ab8a12d-7a31-4671-b68f-d2afceac2109)

**Comment by evernat** [comment]
@gshumakher I am curious for my apps and for anyone apps. For which use case do you use virtual threads ? How many virtual threads do you have at maximum ? And have you seen a measurable improvement in performance compared to standard threads ?
