### ISSUE TITLE
add query/SQL statistics for tomcat jdbc-pool without javamelody proxy DataSource

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javamelody/javamelody#216]
```
Currently the only way to get SQL statistics (get the top-10 of slow queries 
etc.) is using a special proxy DataSource/Driver 
("net.bull.javamelody.JdbcDriver").

With the consequence that every jdbc action is routed through the javamelody 
jdbc driver.

Maybe I am bit conservative but this frightens me, because the successful 
operation of my application totally depends on the javamelody jdbc driver.

How about an alternative to the proxy DataSource?
At least jdbc pool offers at least three ways to hook into the pool to get all 
the information required, with a less invasive manner:

1. Either to connect to a JMX bean to receive notifications
2. To implement an AbstractQueryReport ( 
http://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/tomcat/jdbc/pool/intercep
tor/AbstractQueryReport.html )
3. To implement a JdbcInterceptor ( 
http://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/tomcat/jdbc/pool/JdbcInte
rceptor.html )

```

Original issue reported on code.google.com by `mineral_...@gmx.de` on 7 May 2012 at 4:41

**Comment by ataraxie** [comment]
What is the status of this issue? We just switched from Commons JDBC to Tomcat JDBC and we lost our SQL statistics.

**Comment by evernat** [comment]
@ataraxie 
There is no reason to lose SQL stats when switching to tomcat jdbc pool (if that is what you mean). See [doc](https://github.com/javamelody/javamelody/wiki/UserGuide#7-jdbc) for configuration.

As a side not about tomcat jdbc-pool: DBCP2 performance is now the same as jdbc-pool as said by Mark from Apache. Why switch to jdbc-pool?
About this issue: it is just an enhancement idea to possibly have an alternative implementation. So, this enhancement is not required to have sql stats working. Status is "no high priority".

**Comment by ataraxie** [comment]
Well, it might be true there is "no reason", maybe I did something wrong. I read your manual as well and currently I can't find what I could have done wrong. Basically, what we changed is only that we added _factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"_ to our Resource in server.xml:
```
<Resource 
	name="jdbc/confluence"
	factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
	driverClassName="net.sourceforge.jtds.jdbc.Driver"
	auth="Container"
	type="javax.sql.DataSource"
	username="confluence"
	password="XXXXX"
	url="jdbc:jtds:sqlserver://XXXXX:1433/confluence"
	connectionProperties="useLOBs=false"
	maxActive="100"
	maxIdle="50"
	maxWait="30000"
	minIdle="10"
	initialSize="10"
	validationQuery="select 1" />
```

We changed from DBCP2 to Tomcat JDBC, because we experience quite a few end-of-life situations on Tomcat 8 and after some research have a feeling it's associated with the DB pool. I wouldn't say that I'm sure of that, but we simply wanted to try.

We haven't had any issues so far since we changed the pool. The only issue is that we won't get any more SQL statistics with JavaMelody after we added the _factory_ attribute.

**Comment by evernat** [comment]
ah! this is in Confluence. That's a reason, because in Confluence the undocumented "rewrap-datasource" is true, but datasource rewrapping is not supported for tomcat jdbc-pool. You could try to add a system property -Djavamelody.rewrap-datasources=false but I have never tried that in Confluence. Otherwise, you can switch back to dbcp2.

**Comment by ataraxie** [comment]
Sorry for not mentioning that it's Confluence. Never head of a datasource rewrap. I'll test your proposal. Thanks!

**Comment by jdesmet** [comment]
Facing the same issue with a barebones web application (not confluence) deployed in Tomcat, using the tomcat jdbc-pool: not working after setting the "factor". I know this is an old thread - but is there any update?

**Comment by ataraxie** [comment]
Hmm, I don't quite remember. I think I fiddled around some more and didn't get it to work. Think we just lived without the JDBC statistics after that. Sorry.

**Comment by jdesmet** [comment]
I think I found the problem: I had more than one connection pool, but one of them was failing to setup (invalid username/password). It was ignored because the pool was simply not used, so the application itself continued to function normal. Once I took out the violating connection pool, javamelody registered the pools, and monitoring worked as expected.

I think that still falls in the category of bugs, only thing is that I am not sure if it is something that should be handled by java melody - or is it something that is specific to the connection pools being used, or the registry process within Tomcat.

**Comment by evernat** [comment]
After some years, the tomcat jdbc connection pool is not the default pool in Tomcat (dbcp 2 is the default) and is not very popular (popularity is more decreasing than increasing).
It does not encourage to add a specific implementation for the tomcat jdbc connection pool.
So closing as won't do.
