### ISSUE TITLE
Allow "push" to central server

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javamelody/javamelody#254]
```
In my use case I would like instances of my app which live behind customer's 
firewalls to push their data to a java melody server living in the cloud, 
rather than the central server having to know about all instances and pulling 
from them, which is mostly impossible because of firewalls.
This would be configured in the app by the customer opting in to send 
statistics etc. 


```

Original issue reported on code.google.com by `jon.ner...@gmail.com` on 10 Sep 2012 at 4:57

**Comment by stolp** [comment]
+1

I envision a solution where I am able to receive monitoring data from several instances and browse through them at my leisure. This is the ideal solution for SaaS providers keeping track of their customers systems.

**Comment by ccairns-hae** [comment]
One idea/approach for this is to combine the scheduled email function with the API and every day send the melody API data to a configured URL (of a centralized collector).

**Comment by evernat** [comment]
After some thoughts about this, I think that it is not possible in general, because important data in the monitoring reports need that the collector server calls the monitored app to get the data on demand (in particular, current executing requests, http sessions, database reports, jndi tree, spring beans, dependencies, web.xml, pom.xml, java sources, open connections, heap histogram, processes, hotspots, sql explain plan).

So we can't have only push mode from the monitored app to the collector server.
And this enhancement will be closed as won't fix.

If you really want to use the optional collector server and if you were thinking to put the collector server outside of the firewalls, then I suggest that the collector server should be allowed to call the app(s) to monitor through the firewalls via http(s) or that the collector server must be placed inside the firewalls instead of outside.
Node that using the optional collector is just optional and that the common way is to not use a collector server at all, but just the monitoring inside the app itself (as in the [user guide](https://github.com/javamelody/javamelody/wiki/UserGuide#javamelody-setup)).
