### ISSUE TITLE
Separate functionality into multiple modules

### ISSUE THREAD

**Issue by markathomas** [javamelody/javamelody#504]
Different pieces of functionality in JavaMelody are 'behind the times' and cause problems during upgrades of other pieces of software.  It would be nice to be able to separate the functionality of JavaMelody into separate artifacts that can be included/excluded individually.  Currently, I have conflicts with JPA and Log4J as I am using Hibernate 5.0.2 and Log4J 2.4.1.  Instead of being able to simply exclude the functionality related to these libraries I have to completely disable JavaMelody.

**Comment by evernat** [comment]
We can't extract each feature of JavaMelody into a different module. There would be too many modules and that would be unmaintainable and undocumentable for us, and unusable for users.
By the way, the different modules would not be well chosen or configured depending on unknown cases (example Log4J 2.4.1).

In fact, "JavaMelody just works with as less as possible configuration" is a choice since the beginning (that may be different than some commercial softwares with a lot of configuration or than some OSS with a lot of modules.)

So if there is an issue with Hibernate 5.0.2 or Log4J 2.4.1, you should if needed create an issue or better a pull request, or you can write some documentation for the wiki.
