### ISSUE TITLE
Filters in web.xml not working with Jetty

### ISSUE THREAD

**Issue by darkaeon10** [javamelody/javamelody#508]
Hi, I've recently added Java Melody to a grails application. So I wanted to restrict the IP addresses that can access the monitoring endpoint, and also add basic auth for it so that not anyone can access the monitoring endpoint once the application is released for public use. I've added filters to my web.xml, according to your documentation. They look like this:

```
    <filter>
	    <filter-name>javamelody</filter-name>
	    <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
	    <init-param>
	        <param-name>authorized-users</param-name>
	        <param-value>user1:pwd1</param-value>
	    </init-param>
	    <init-param>
			<param-name>allowed-addr-pattern</param-name>
			<param-value>192\.168\.1\.*</param-value>
        </init-param>
	</filter>
	
    <filter-mapping>
            <filter-name>javamelody</filter-name>
            <url-pattern>/monitoring</url-pattern>
    </filter-mapping>
```

I've verified that it works when I run the application using  *grails run-app*. If i try to access the monitoring endpoint, I am prompted for a username and password. However, when I create a war file and deploy it to run on a jetty instance, the security filters don't work anymore. I can access the monitoring endpoint without providing a username and password. 

Can anyone help me with this? I really don't know how to proceed with this problem. Appreciate all the help I can get. Thanks!

**Comment by evernat** [comment]
If you have a grails app, you may certainly use the [javamelody grails plugin](http://www.grails.org/plugin/grails-melody)
If you use this plugin, you can add in your grails-app/conf/GrailsMelodyConfig.groovy the following (without modifying your web.xml file):
javamelody.'authorized-users' = 'user1:pwd1'
javamelody.'allowed-addr-pattern' = '192\.168\.1\.*'

Otherwise you can add system properties for example:
-Djavamelody.authorized-users=user1:pwd1 -Djavamelody.allowed-addr-pattern=192\.168\.1\.*

Reference: http://www.grails.org/plugin/grails-melody
