### ISSUE TITLE
Scripts and alerts in live environment without Jenkins

### ISSUE THREAD

**Issue by nicolasrosado** [javamelody/javamelody#536]
Hi,

In your documentation about "ScriptsAndAlerts", you specify that we need jenkins to create some groovy scripts and send some alerts. 

But how can we use scripts and alerts in live environment without jenkins ?

Is this functionnality available ? Do we need to schedule some groovy scripts in live environment to get  the same behavior ? 

For my company we need to send weekly, daily or monthly reports by mail and we need to set alerts depends on some threshold so if I'm able to use scripts and alerts in live environment without Jenkins I will appreciate a lot.

Thanks in advance for your time and your response.

**Comment by UrielSarrazin** [comment]
This feature would be nice !!!

**Comment by evernat** [comment]
1. Sending weekly, daily or monthly reports by mails is already possible, look at
https://github.com/javamelody/javamelody/wiki/UserGuide#14-weekly-daily-or-monthly-reports-by-mail
2. To execute groovy scripts and send alerts, it is [documented](https://github.com/javamelody/javamelody/wiki/ScriptsAndAlerts) to use Jenkins and it's not currently documented otherwise. But being able to do the same without Jenkins is a good idea, so I have created issue #537.

**Comment by evernat** [comment]
Of course you can already write your own scripts [like this](https://wiki.jenkins-ci.org/display/JENKINS/Monitoring+Scripts) or using [External API](https://github.com/javamelody/javamelody/wiki/ExternalAPI)
