### ISSUE TITLE
Workaround for bad JPA request naming using Hibernate ORM

### ISSUE THREAD

**Issue by HonoluluHenk** [javamelody/javamelody#563]
With (at least) Hibernate as JPA provider, counter request names for createQuery() with CriteriaQuery, CriteriaUpdate, CriteriaDelete() are kinda unusable in the JPA section:

Each and every single executed Query displays as a new monitoring entry  like:
Query(org.hibernate.jpa.criteria.CriteriaQueryImpl@1b0gcb0)

As you already pointed out in #560 the final solution would be to make the JPA provider team implement a toString() method.

Seems like this is not going to happen anytime soon and backports to older hibernate versions are not on the horizon :(

A standardized (Java-)interface to custom naming schemas for request names would be cool.

**Comment by HonoluluHenk** [comment]
Possible implementation of a naming strategy: see pull request #564

**Comment by evernat** [comment]
@HonoluluHenk 
For hibernate impl, it seems that there is a project to transform a criteria to a jpql String:
https://sourceforge.net/projects/criteria2jpql/
I have not looked at the source but it shows that it is possible.

Otherwise transforming a crtieria to a sql String (without parameter values) seems easier for hibernate. See for example:
http://stackoverflow.com/questions/554481/how-to-get-sql-from-hibernate-criteria-api-not-for-logging
So it shows that it would be quite easy for hibernate to implement a toString() method such as "CriteriaUpdate[update blabla ...]"
It would be good in my opinion.

For reference:
https://hibernate.atlassian.net/browse/HHH-10980

That said I will look at the PR.

**Comment by HonoluluHenk** [comment]
Latest changes, see: #567

**Comment by evernat** [comment]
#567 is merged so closing this issue.
And we will wait for implementation of https://hibernate.atlassian.net/browse/HHH-10980
