### ISSUE TITLE
ehcache3 support

### ISSUE THREAD

**Issue by pethers** [javamelody/javamelody#574]
Plan to upgrade ehcache3 at some point, would miss the ehcache information provided by javamelody so did some tests.

Tried to compile with
<dependency>
  <groupId>org.ehcache</groupId>
  <artifactId>ehcache</artifactId>
  <version>3.1.1</version>
</dependency>

Package has moved from net.sf.ehcache to org.ehcache and some changed names or been replaced.

Breaks net.bull.javamelody.Action and net.bull.javamelody.CacheInformations, could possible use org.ehcache.jsr107.Eh107CacheStatisticsMXBean to get statistics.

Happy to help out, but what would be the prefered way to support another cache provider ?

**Comment by ben-manes** [comment]
Ehcache 3 moved to MRU eviction policy (in milestone 5, from LRU) and has an `O(n)` eviction policy due to their rewritten sampling scheme. That tends to result in **much** worse performance, so you probably want to benchmark to ensure there isn't a negative impact.

Since v3 uses the JCache API and there is a v2 adapter, you can migrate the code over and switch easily switch providers. Should make it easy to experiment to ensure an upgrade doesn't have a negative impact.

**Comment by evernat** [comment]
I see that there are a lot of changes in the ehcache api. So reading values will be quite different than before.
So I suggest to create a new class extending the old class and its getters.

And then a choice would be between compatibility of javamelody will all JSR107 impls and compatibility with just ehcache 3 but perhaps with more details.
For example of this new class, using [javax.cache.management.CacheStatisticsMXBean](http://grepcode.com/file/repo1.maven.org/maven2/javax.cache/cache-api/1.0.0/javax/cache/management/CacheStatisticsMXBean.java?av=f):
```java
class CacheInformations2 extends CacheInformations {
	private static final boolean 107CACHE_AVAILABLE = is107CacheAvailable();
	private final String name;
	private final long inMemoryObjectCount;
	private final int inMemoryPercentUsed;
	private final long onDiskObjectCount;
	private final long inMemoryHits;
	private final long cacheHits;
	private final long cacheMisses;
	private final String configuration;

	private CacheInformations2(MBeans mBeans, ObjectName cache) throws JMException {
		super(); // this needs a new empty constructor
		name = cache.getKeyProperty("name");
		cacheHits = (Long) mBeans.getAttribute(cache, "cacheHits");
                ...
	}

	private static boolean is107CacheAvailable() {
		try {
			Class.forName("javax.cache.Cache");
			return true;
		} catch (final ClassNotFoundException e) {
			return false;
		}
	}

	static List<CacheInformations> buildCacheInformationsList() {
		if (!107CACHE_AVAILABLE) {
			return Collections.emptyList();
		}
		final MBeans mBeans = new MBeans();
                final Set<ObjectName> caches = mBeans.get107CacheStatistics();
		final List<CacheInformations> result = new ArrayList<>(caches.size());
		for (final CacheStatisticsMXBean cache : caches) {
			result.add(new CacheInformations2(mBeans, cache);
		}
		return result;
	}

	@Override
	String getName() {
		return name;
	}

	@Override
	long getInMemoryObjectCount() {
		return inMemoryObjectCount;
	}

	@Override
	long getInMemoryPercentUsed() {
		return inMemoryPercentUsed;
	}

	@Override
	long getOnDiskObjectCount() {
		return onDiskObjectCount;
	}

	// efficacité en pourcentage du cache mémoire par rapport au cache disque
	@Override
	int getInMemoryHitsRatio() {
		if (cacheHits == 0) {
			return -1;
		}
		return (int) (100 * inMemoryHits / cacheHits);
	}

	// efficacité en pourcentage du cache (mémoire + disque) par rapport au total des accès
	@Override
	int getHitsRatio() {
		final long accessCount = cacheHits + cacheMisses;
		if (accessCount == 0) {
			return -1;
		}
		return (int) (100 * cacheHits / accessCount);
	}

	@Override
	String getConfiguration() {
		return configuration;
	}
}
```

with in MBeans:
```java
	Set<ObjectName> get107CacheStatistics() throws MalformedObjectNameException {
		return mbeanServer.queryNames(new ObjectName("javax.cache:type=CacheStatistics,*"), null);
	}
```
(I have tested nothing at the moment.)

**Comment by ben-manes** [comment]
Oh, by luck they just released `3.1.2` which is comparable with `2.10`. Its weird that they don't mention the change in the release notes. There is no indication why after nearly a year of refusing to fix it they suddenly did. I'm glad its finally resolved, though.

Policy | Hit rate | Requests | Time
---|---|---|---
Ehcache 2.10 | 33.16 % | 42,243,785 | 1.619 min
Ehcache 3.1.1 | 23.89 % | 42,243,785 | 3.541 min
Ehcache 3.1.2 | 31.48 % | 42,243,785 | 2.188 min
Caffeine 2.3.3 | 48.27 % | 42,243,785 | 12.11 s

Concurrency-wise performance is about 50% better, but still lackluster.

Anyway, sorry for the noise since its comparable enough to no longer be an upgrade concern.

**Comment by evernat** [comment]
@ben-manes 
Glad to see you here. I suppose that you already use javamelody for monitoring of your apps. If it is not yet the case, you should try it now.

**Comment by ben-manes** [comment]
@evernat Thanks. I was reviewing my options and thinking of projects for a new hire, so stumbled onto this task. Right now we have failure monitoring, but don't eyeball the health. So needs to be done, just been on the back burner given the small scale of a startup.

**Comment by pethers** [comment]
Thanks for all feedback. 

Did some test didn't managed to get it to display any data,  but couldn't find any cache statisticts mbean in jconsole either so probably did something wrong enabling the stats.

--
	<bean id="cacheManager" class="org.springframework.cache.jcache.JCacheCacheManager">
	      <property name="cacheManager" ref="jCacheManager" />
	</bean>
	
	<bean id="jCacheManager" class="org.springframework.cache.jcache.JCacheManagerFactoryBean">
	     <property name="cacheManagerUri"   value="classpath:ehcache3.xml" /> 	
	</bean>
--

ehcache3.xm
--
<config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://www.ehcache.org/v3'
    xmlns:jsr107='http://www.ehcache.org/v3/jsr107'
    xsi:schemaLocation="
        http://www.ehcache.org/v3 http://www.ehcache.org/schema/ehcache-core-3.1.xsd
        http://www.ehcache.org/v3/jsr107 http://www.ehcache.org/schema/ehcache-107-ext-3.1.xsd">


  <service>
    <jsr107:defaults enable-management="true" enable-statistics="true" />
  </service>

</config>
--

Looks like ehcache3 is not supporting hibernate.cache.default_cache_concurrency_strategy TRANSACTIONAL yet, will have to stay with ehcache2 for some time.

**Comment by pethers** [comment]
Moved to ehcache 3.5.2 now, miss the cache stats so will have not forgot about this one yet. Will do some more test using CacheStatisticsMXBean soon.

**Comment by stolp** [comment]
I am currently evaluating a move to ehcache 3.x in our application, which is currently using ehcache 2. 

I like to throw in a vote for supporting this. I would be really missing the cache access statistics here.

Is there any chance to see this supported?

**Comment by pethers** [comment]
@stolp might have some soon. See data in CacheStatistics in MBeans now, so slow progress.

**Comment by ben-manes** [comment]
FYI, the later versions of Ehcache3 cannot coexist with Ehcache2 (https://github.com/ehcache/ehcache3/issues/2334), intentionally. This could be problematic if an application tries to partially migrate, e.g. has a dependency that uses a different version. So you may need to be clear in any migration documentation as users might run into issues. Using JCache is probably the best choice then, since there is an official (but abandoned) ehcache2 adapter which could ease the transition.

**Comment by stolp** [comment]
@ben-manes thanks for the heads-up. Luckily, ehcache2 is already history and the move to ehcache3 is complete now.

**Comment by pethers** [comment]
Some progress, far from perfect but at least it displays some data now ![cache-overview](https://user-images.githubusercontent.com/1726836/42844004-05c65684-8a12-11e8-8852-884faa597f4e.png)

Did reuse CacheInformations to get something displayed, but will create a pull request once I figured out howto clean it up properly.

**Comment by gabivis** [comment]
Any updates on this? Still not possible to use java melody with ehcache 3?

**Comment by pethers** [comment]
Haven't done any more work since last comment, not sure I will complete it anytime soon.

**Comment by susp248** [comment]
So sad. I am also looking forward to see this finally supported.

**Comment by stolp** [comment]
+1

I am still missing EHCache 3 support badly.

**Comment by evernat** [comment]
added support of jcache (javax cache api) and of ehcache3, including for each cache: hits vs misses ratio, cache keys and clear actions.
Commit: dc094d6, to be released in v1.78.

For this, I have taken up the work of James Pether Sörling. Then I have separated the classes for ehcache and for jcache, because attributes and api are very different between ehcache and jcache.
Thanks @pethers

**Comment by evernat** [comment]
It is needed to enable JCache statistics for caches to be displayed in the reports.
For example, add the following in your ehcache.xml:
```xml
  <service>
    <jsr107:defaults enable-management="true" enable-statistics="true"/> 
  </service>
```

**Comment by stolp** [comment]
@evernat Thanks a lot, much appreciated!

**Comment by evernat** [comment]
A snapshot build is available at:
http://javamelody.org/downloads/javamelody-core-1.78.0-SNAPSHOT.jar

**Comment by gabivis** [comment]
@evernat Thanks a lot!

**Comment by stolp** [comment]
@evernat I tested the snapshot with our application and it is working as announced. I still miss the more detailed caching information (e.g. number of elements in cache) from the ehcache2 implementation but I assume this is out of scope with jcache.

Thanks!

**Comment by evernat** [comment]
@stolp 
If you click on the name of a cache, you will have the list of keys and also the number of keys (and of elements) for that cache. So you still have that.
But that can be done only when you ask for it and that can't be done for every cache every time, because iterating over every elements may be a bit expensive sometimes.

**Comment by stolp** [comment]
Its true - I was missing the links. Yet when I click on them I receive a blank page although the cache does contain elements. Let me know if I can add details to this.

**Comment by evernat** [comment]
Yes, please open a new issue and look if there is a stack trace in the server logs. Thanks.

**Comment by maks1212** [comment]
I cannot delete or see details from the cache im using javamelody 2.0.1 and Spring boot 3 with ehcache 3. Is this normal or do i miss something in my config?
![image](https://github.com/javamelody/javamelody/assets/30495329/6d60a890-12b9-4960-b404-e6c01b1bf1cc)
