### ISSUE TITLE
Total http session value and total bytes received / sent per minute ....

### ISSUE THREAD

**Issue by gallirobe** [javamelody/javamelody#580]
Good afternoon everyone,
I have javamelody "activated" on alfresco installation. It works very very well...
But if i want to know the total amount of http sessions by day/week/months.... or the total of bytes received-sent by day/week/months i cannot.....
Because the graph tell me only the Mean and the Maximum....
Is there something i can do to modify this graph to tell me the total ?
If not, is it possible to implement a new version of javamelody in which there is the total ?
Many Thanks 

Roberto

**Comment by evernat** [comment]
You can not modify the graph.
But you can tell the number of total bytes received/sent by day/week/month.

For example, each value in the graph is the bytes sent for a minute and there is a value each minute. We know that the mean at the bottom of the graph is the sum of all values divided by the number of values. And we know that the number of values is the number of minutes in the period. So the sum and the total bytes is the mean multiplied by the number of minutes.

We can't do the same to have the total number of http sessions, because a value in the http sessions graph is the number of existing sessions and not the number of created sessions, so a session will be counted with others during several minutes.
But there is another graph in "Other charts": the mean age of http sessions in minutes. This mean age in minutes will allow to have the mean duration of http sessions and to rectify the number of http sessions.

For example, with the attached graphs of a week on a server (a Liferay server):
- the mean of bytes received per minute 16 KB  (for all webapps, when using Tomcat)
- the mean of bytes sent per minute is 7 MB (idem)
- the mean of http sessions is 117
- the mean age of http sessions is 16, so the mean duration is approximately 16 * 2 = 32 minutes (in fact, most visitors are active for 2 minutes and then session timeout is 30 minutes in this webapp)
![graphs1](https://cloud.githubusercontent.com/assets/498950/19221732/29516b8c-8e49-11e6-83c9-478ff9cba163.png)
![graphs2](https://cloud.githubusercontent.com/assets/498950/19221735/2fb07c0c-8e49-11e6-823f-eabd0eee34dc.png)

So the total bytes received for this week is 16 KB * 7 * 24 * 60 = 161 MB
The total bytes sent is 7 MB * 7 * 24 * 60 = 71 GB
The number of http sessions is 117 * 7 * 24 * 60 / (16 * 2) = 37000 sessions
(In fact, those values are for one server in a cluster of two, so I have to multiply the values by 2 to have the total.)

Note: The units in the charts are chosen based on the values: "m" is for milli (1 / 1000), "k" is for kilo/thousands, "M" is for mega/millions, "G" is for giga/billions and "u" is for micro (1 / 1000000).
