### ISSUE TITLE
@Async + MonitoringSpringAdvisor not executed asynchronously

### ISSUE THREAD

**Issue by rodrik** [javamelody/javamelody#582]
My methods annotated with @Async  lost the asynchronous ability after I installed JavaMelody in the application. I'm using the following configuration:
`@Bean
	public MonitoringSpringAdvisor springServiceMonitoringAdvisor() {
		final MonitoringSpringAdvisor interceptor = new MonitoringSpringAdvisor();
		interceptor.setPointcut(new AnnotationMatchingPointcut(Service.class));
		return interceptor;
	}`

The only way to solve was to change my class from `@Service` to `@Component`, but then I cannot monitor that spring bean.

**Comment by evernat** [comment]
I do not reproduce the issue.
I have a `@Service` method annotated with `@Async` and the Application class is annotated with `@SpringBootApplication` and `@EnableAsync`
And the method call is correctly asynchronous. The execution time of the method in the monitoring stats is the real time of the method (not just 0).

Perhaps you have forgotten `@EnableAsync` ?
Otherwise can you give the source of a simple project to reproduce the issue ?

**Comment by evernat** [comment]
Any news ?

**Comment by rodrik** [comment]
In the next 10 days I'll retest this. Thanks for reminding me.

**Comment by evernat** [comment]
No response from @rodrik , so closing this for the moment.
If you have more info, we can reopen the issue.
