### ISSUE TITLE
ClassNotFound exception when doing heap dump on wildfly 10

### ISSUE THREAD

**Issue by huangp** [javamelody/javamelody#585]
`
Caused by: java.lang.ClassNotFoundException: com.sun.management.HotSpotDiagnosticMXBean from [Module "deployment.ROOT.war:main" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
`

Adding `<path name="com/sun/management"/>` to wildfly's "sun.jdk" module will fix the problem. But editing wildfly's built-in modules is not ideal. Anything javamelody can do?

**Comment by seanf** [comment]
See also https://github.com/javamelody/javamelody/issues/133 for a similar problem on JBoss AS 7.

**Comment by evernat** [comment]
Currently there is no other workaround for using this feature in wildfly 10, than to add<path name="com/sun/management"/> to wildfly's "sun.jdk" module.
But issue #133 was fixed by this commit (c15c9b46ab1c7a16285cad8abc23f4f12008e4af#diff-d59e6e98178dc3fd757c870deae30b73), and no configuration is needed anymore for #133.

Perhaps something similar using reflection can be used to fix this issue for heap dump.
The code to change for using reflection is in this method:
https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/Action.java#L311

**Comment by evernat** [comment]
The fix for compatibility of the heap dump with JDK 9 in javamelody 1.73.1 has certainly fixed this issue in all Oracle/Sun JDK. So closing as fixed.
