### ISSUE TITLE
Java Melody CA PPM

### ISSUE THREAD

**Issue by ppmspartan** [javamelody/javamelody#593]
Hello, we have CA PPM versión 14.2 (Tomcat 7.0.55) and i just installed Javamelody. The CA PPM instance uses a JNDI connection to connect to its Microsoft SQL Server 2008 database. While viewing the javamelody graphs, none of the SQL graphs populate, along with the SQL statistics area.
Here the debugging Log:

Wed Dec 07 08:42:17 CET 2016     DEBUG     Server: CA Clarity PPM
Wed Dec 07 08:42:17 CET 2016     DEBUG     Webapp context: /
Wed Dec 07 08:42:17 CET 2016     DEBUG     JavaMelody version: 1.62.0
Wed Dec 07 08:42:17 CET 2016     DEBUG     JavaMelody classes loaded from: file:/C:/Clarity/niku/lib/javamelody.jar
Wed Dec 07 08:42:17 CET 2016     DEBUG     Host: APPDEV@x.x.xxx.xxx
Wed Dec 07 08:42:17 CET 2016     DEBUG     parameter defined: datasources=jdbc/NikuDS
Wed Dec 07 08:42:17 CET 2016     DEBUG     log listeners initialized
Wed Dec 07 08:42:17 CET 2016     DEBUG     rebinding datasources failed, skipping
Wed Dec 07 08:42:17 CET 2016     DEBUG     counters initialized
Wed Dec 07 08:42:17 CET 2016     DEBUG     counters data read from files in C:\Clarity\niku\tomcat-app-deploy\temp\javamelody\_APPDEV
Wed Dec 07 08:42:17 CET 2016     DEBUG     collect task scheduled every 60s
Wed Dec 07 08:42:18 CET 2016     DEBUG     first collect of data done
Wed Dec 07 08:42:18 CET 2016     DEBUG     JavaMelody filter init done in 826 ms

Any help would be apreciate.

Thanks

**Comment by evernat** [comment]
I have never looked at CA PPM, so I don't know why except "rebinding datasources failed, skipping" in the debugging logs.
But I suggest to try the "rewrap-datasources" javamelody parameter, like you have added the "datasources" parameter.
For example: -Djavameldoy.rewrap-datasources=true
This is an undocumented parameter but it may be tried when you use a jdbc datasource from JNDI.

Let us know if it works.

**Comment by ppmspartan** [comment]
Thank you .
I added the parameter -Djavamelody.rewrap-datasources=true. Let me explain some test performed:

- if i remain the parameter -Djavamelody.datasources=jdbc/NikuDS the rebinding datasource are still failed.
- if i remove -Djavamelody.datasources=jdbc/NikuDS it seems that rebinding datasources are not failed but SQL stadistics and SQL charts don't show any data.

The Debugging logs now (without datasource parameter & with rewrap=true parameter) is:

```
Thu Dec 15 15:49:33 CET 2016     DEBUG     OS: Windows Server 2008 R2 Service Pack 1, amd64/64
Thu Dec 15 15:49:33 CET 2016     DEBUG     Java: Java(TM) SE Runtime Environment, 1.7.0_67-b01
Thu Dec 15 15:49:33 CET 2016     DEBUG     Server: CA Clarity PPM
Thu Dec 15 15:49:33 CET 2016     DEBUG     Webapp context: /
Thu Dec 15 15:49:33 CET 2016     DEBUG     JavaMelody version: 1.62.0
Thu Dec 15 15:49:33 CET 2016     DEBUG     JavaMelody classes loaded from: file:/C:/Clarity/niku/lib/javamelody.jar
Thu Dec 15 15:49:33 CET 2016     DEBUG     Host: APPDEV@1.216.82.52
Thu Dec 15 15:49:33 CET 2016     DEBUG     log listeners initialized
Thu Dec 15 15:49:33 CET 2016     DEBUG     datasources found in JNDI: []
Thu Dec 15 15:49:33 CET 2016     DEBUG     counters initialized
Thu Dec 15 15:49:33 CET 2016     DEBUG     counters data read from files in C:\Clarity\niku\tomcat-app-deploy\temp\javamelody\_APPDEV
Thu Dec 15 15:49:33 CET 2016     DEBUG     collect task scheduled every 60s
Thu Dec 15 15:49:34 CET 2016     DEBUG     first collect of data done
Thu Dec 15 15:49:34 CET 2016     DEBUG     JavaMelody filter init done in 1560 ms
```

**Comment by evernat** [comment]
You should add again `-Djavamelody.datasources=jdbc/NikuDS` otherwise the datasource is not found in JNDI.
And for some reason, the `-Djavamelody.rewrap-datasources=true` parameter is not seen by javamelody, according to debugging logs.
So I suggest to check how you have added that parameter. And note also that there are several means to add the parameter in case one does not work for you: in conf/catalina.properties, in context param of conf/localhost/youcontext.xml or on command line like you seem to have used.

By the way, I don't understand why the javamelody.jar is in the directory C:/Clarity/niku/lib/
while the tomcat directory seems to be C:\Clarity\niku\tomcat-app-deploy
Perhaps you should put the javamelody.jar file in the WEB-INF/lib directory of your webapp as it is supposed to be.

Anyway, there is no bug on the horizon. So I close this issue as of now. You can still add comments and I will probably answer if I can.
