### ISSUE TITLE
How to use Javamelody with OpenJPA

### ISSUE THREAD

**Issue by frederik78** [javamelody/javamelody#608]
Hello...
I am trying to add Javamelody on a legacy webbapp running on Websphere 7. And I am stucked with OpenJPA 1.2.2. 

The problem is in the wiki it is described how to add the javamelody driver with Hibernate. (<property name="hibernate.connection.driver_class">net.bull.javamelody.JdbcDriver</property>) but not with others ORM's vendor.

How to make the same think with OpenJPA?

Regards

Frédéric

**Comment by evernat** [comment]
Websphere 7 ? Oh my god !

First, the support of automatic SQL monitoring in obsolete Websphere is not a priority (Websphere users for javamelody are something like 0.01% and less than anything else, ie Tomcat, TomEE, jetty, Resin, Pivotal, Glassfish, Paraya, Undertow, WildFly, JBoss, Weblogic).

Inside OpenJPA without automatic SQL monitoring, it depends. But if you use a datasource from jndi in OpenJPA, that's good for you and you can't use net.bull.javamelody.JdbcDriver.
If you use a jdbc driver instead of a datasource, as far as I know you may try :
<property name="openjpa.ConnectionDriverName" value="net.bull.javamelody.JdbcDriver"/>
<property name="openjpa.ConnectionProperties" value="driver=com.mysql.jdbc.Driver"/>

Good luck (if you still have luck somewhere)
