### ISSUE TITLE
Allow http-transform-pattern aggregation to match regex groups

### ISSUE THREAD

**Issue by jshnaidman** [javamelody/javamelody#649]
Currently the value set by the [http-transform-pattern](https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters) parameter in the web.xml will transform descriptions of http requests by replacing all matches found by the regular-expression, including all matched groups, by a $. This will always include group 0 which will be the whole string that matches the regex pattern. This makes aggregation very limited since it will always aggregate the entire match of the regex pattern regardless of what group you're trying to match. 

Perhaps changing the logic of getAggregateRequestName in javamelody-core/src/main/java/net/bull/javamelody/internal/model/Counter.java to take into account different groups instead of using  matcher.replaceAll(TRANSFORM_REPLACEMENT) would work.

**Comment by evernat** [comment]
1. Can you give an example or two of initial requests you have and of transformed requests you would want?
2. What code in getAggregateRequestName would do what you want?

**Comment by Jshn245** [comment]
Let's say I have a string "/somerepository/23423/2342234/64564/filename PUT"

I would like to have this aggregated under /somerepository/$ PUT
If I tried a regular expression with ^/[^/]*/(.*) PUT$ this would aggregate under $ instead of /somerepository/$ PUT 


I have not tested whether this works at all, it is just a suggestion, but maybe something like

if (matcher.groupCount() > 1){
				for (i=1; i<= matcher.groupCount(); i++){
					matcher.group(i).replaceAll(TRANSFORM_REPLACEMENT);
				}
			}

This way, you avoid group 0 which matches the entire string if the regular expression contains groups that the user would like to match.

**Comment by evernat** [comment]
I don't understand your regexp, but would it be enough to use a positive lookbehind?
Something like `(?<=/somerepository/).*`

**Comment by Jshn245** [comment]
The lookbehind wouldn't work if I used a quantifier. It needs to match repositories with many different names.

**Comment by evernat** [comment]
Finally, I have looked more at this and at the PR.
And it will be closed without merge, because 
1. you can already do this without any change.
That is, you can already aggregate  "/somerepository/23423/2342234/64564/filename PUT" to  "/somerepository/$ PUT" with the regexp `(?<=[^/]+/)[^ ]+` or if you prefer with the regexp `(?<=[a-z]+/)[0-9a-z/]+`.
2. the performance would be affected (matcher.matches() then matcher.replaceAll(String) instead of just matcher.replaceAll(String)) in a critical path for every user when having the http-transform-pattern parameter or any *-transform-pattern parameter. And the performance may not be great either when having groups matching and replacing as you suggest.

Thanks anyway for the suggestion.
