### ISSUE TITLE
Is authentication with Shiro possible?

### ISSUE THREAD

**Issue by tommc3** [javamelody/javamelody#653]
We have a Spring Boot application (version 1.5.3).  Can we use a Authorizing Realm https://shiro.apache.org/static/1.2.2/apidocs/org/apache/shiro/realm/AuthorizingRealm.html for authentication?  In our case the credentials are stored in a Postgres database.

We are currently using basic auth
`javaMelody.addInitParameter(Parameter.AUTHORIZED_USERS.getCode(), "admin:pwd");`

**Comment by evernat** [comment]
sorry, Shiro is not suppported for authentication.
All supported authentications are here:
https://github.com/javamelody/javamelody/wiki/UserGuide#16-security

**Comment by ricardolsmendes** [comment]
Hi there,
I understand Shiro is not supported for authentication but is there any known issue when running both JavaMelody and Shiro in a Spring Boot application?

I'm working on modernizing a web application that has used Java Melody and Shiro for more than 8 years (_standard_ deployment to Tomcat through a `war` file). The migration to Spring Boot with embedded Tomcat is almost done, but Shiro seems to break when Java Melody's Spring Boot Starter is set up. The error message is:
```
org.apache.shiro.UnavailableSecurityManagerException: No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.
```
I've also tried [integrating without the Spring Boot Starter](https://github.com/javamelody/javamelody/wiki/SpringBootStarter#or-integration-without-the-spring-boot-starter), but the issue persists.

Thoughts? 🤔

**Comment by evernat** [comment]
The comment in July 2017 was that Shiro and in that case Shiro's AuthorizingRealm is not supported for authentication on the monitoring page. I do not remember the details for this assertion (3 years ago), instead of just saying that authentication on the monitoring page is not documented and unknown territory with Shiro and Shiro's AuthorizingRealm.
Anyway that was just for the monitoring page. javamelody should of course not break when using Shiro for the application itself. That would be another valid issue.

It's good to know that Shiro can also be used to restrict access on the monitoring page as you said.
And I agree that there is probably a bug in Shiro spring-boot-starter, so I have added a comment in your Shiro's issue.
