### ISSUE TITLE
How many applications does JavaMelody collector support?

### ISSUE THREAD

**Issue by Zidedine** [javamelody/javamelody#675]
Hi, JavaMelody is amazing. Great job!. 

I would like to tell you our experience to contribute to possible javamelody enhancements:

We have 60 applications linked in javamelody collector. 

We noticed that, with 60 applications with intensive use, we reach early a lot of GB of used space by *.gz and *.rrd files. If we don't clean javamelody statistics folder passed two months, we get java GC errors, as "overhead limit exceeded". ¿What could we do to reduce this used space?, ¿only apply transform patterns?.

Also, we would like to suggest you to implement some kind of **paginable list of applications in javamelody collector interface**. The drop down list with so many applications is hard to handle.

Thank you & congratulations for the great project.

**Comment by evernat** [comment]
> Hi, JavaMelody is amazing. Great job!.

Thanks

> We noticed that, with 60 applications with intensive use, we reach early a lot of GB of used space by *.gz and *.rrd files. If we don't clean javamelody statistics folder passed two months, we get java GC errors, as "overhead limit exceeded". ¿What could we do to reduce this used space?, ¿only apply transform patterns?.

Yes, if you have many http*.rrd files (for example 10000 of them for an application) and if you have requests like "/get/entity/123" for example in the http statistics in the report of the application, then you should set `\d+` for http-transform-pattern **in the monitored application**. (It's the same for sql*.rrd files and sql-transform-pattern.)

Otherwise, you could set the parameters obsolete-graphs-days (default is 90) and obsolete-stats-days (default is 365) in the collector server (the obsolete files will be automatically deleted at midnight). But that would not be really effective for GC errors.
So if you don't use http-transform-pattern and sql-transform-pattern, have you set enough of Xmx for the collector server? If yes, how much?

> Also, we would like to suggest you to implement some kind of paginable list of applications in javamelody collector interface. The drop down list with so many applications is hard to handle.

yes, I will probably add a new page to choose the application when there are more than ~30 in the drop down list.

> How many applications does JavaMelody collector support?

I was already aware of a collector server with 40 monitored applications. The collector server can support a lot more than 60 monitored applications provided than there is more than 1 single cpu and for example 1 GB of memory for the collector: that's not a lot to ask.

**Comment by Zidedine** [comment]
- We have set this parameters **-Xms1512m -Xmx1512m**
- We reach 8GB of space on disk used by rrd and gz files between all applications monitorized.
- Server with **4 cores** - AMD Opteron 62xx class CPU

**Comment by evernat** [comment]
In absolute terms, Xmx and CPUs seem ok to me (for 60 monitored applications).
Given 8GB of disk used, that's a mean of 133 MB by applications, which seems high.
So yes, http-transform-pattern and/or sql-transform-pattern is recommended in the monitored application as said above, for the applications using the most disk space.

**Comment by evernat** [comment]
I have finally changed the display of the list of the applications in the collector server, when there are more than 10 applications. In that case, a table with 5 columns is now displayed (without a new page) instead of applications one below the other. So it will be better when there are 60 applications for example.

It's pushed (ee42200) and ready for the next release (1.71).
You can download a snapshot at:
https://javamelody.ci.cloudbees.com/job/javamelody-collector-server/net.bull.javamelody$javamelody-collector-server/

**Comment by Zidedine** [comment]
Works great! And it's better for manage the monitorized applications. Thank you very much!.
