### ISSUE TITLE
Multiple servers in a Wildfly server groups put collected data files to same place

### ISSUE THREAD

**Issue by KAMI911** [javamelody/javamelody#692]
It seems there is a bug that causes data loss when the one uses Wildfly and there are same more than one Wildfly server (JVM) on same application server. All server will put their data to same tmp subfolder hence they only create one set of graphs. Is there any way to autodetect these situations and modify the javamelody.storage-directory automatically? It would be nice to put Wildfly server name or used port to the auto generated storage directory path that can avoid this bug.

**Comment by evernat** [comment]
Detecting that 2 instances write to the same storage directory is very possible and desirable. (`java.nio.channels.FileChannel.tryLock` would do the job I suppose.)
So it could warn in the reports about the problem.

Wildfly server name or used port will probably not be added to the storage directory (because first, it will change the default currently used by a lot of apps and server name or port would not be a good idea in general).

**Comment by BrommD** [comment]
Why not use the parameter "-Djavamelody.application-name=my_instance" and let JavaMelody add it to the folder name, like "/tmp/javamelody_my_instance". This is a common approach with multiple Jboss Wildfly on same server.

**Comment by evernat** [comment]
@BrommD Yes, it would work well.

Another approach is to use a different "storage-directory" parameter in each instance. For example in system properties: "-Djavamelody.storage-directory=/tmp/javamelody_my_instance"

**Comment by evernat** [comment]
It's done (3863b31) and ready for the next release (1.71): there is now a warning in the reports if multiple instances use the same storage directory.
