### ISSUE TITLE
Used Memory Weekly Graphs showing the continuous increment for JIRA

### ISSUE THREAD

**Issue by suyashjain** [javamelody/javamelody#693]
Hi,

I have 4 instance of JIRA where I have installed the Java Melody v1.69. The day graph looks perfect but when I look for weekly graph, it shows that "Used Memory" and "Available Memory" is increasing on regular bases and there is no pattern as expected and graphs are just going up only.

I tested the same with other tools and they seems to be perfect and providing weekly/monthly graphs as expected.

I have attached the various screenshots for your reference.

![confluence-day](https://user-images.githubusercontent.com/3862495/32427978-7784cf8a-c2e9-11e7-96dc-f4e1b2704553.png)
![crowd-day](https://user-images.githubusercontent.com/3862495/32427979-77c18d9e-c2e9-11e7-826d-e3b0f2ba7218.png)
![crowd-week](https://user-images.githubusercontent.com/3862495/32427981-781087a0-c2e9-11e7-8b47-d4b61a5350eb.png)
![jira2-day](https://user-images.githubusercontent.com/3862495/32427982-784b614a-c2e9-11e7-9c7a-0b00a44bf12c.png)
![jira2-week](https://user-images.githubusercontent.com/3862495/32427983-7884aaf4-c2e9-11e7-89df-be5b1f97cfb6.png)
![jira3-day](https://user-images.githubusercontent.com/3862495/32427984-78bd32f2-c2e9-11e7-841e-3ee85f92b315.png)
![jira3-week](https://user-images.githubusercontent.com/3862495/32427985-78f594ee-c2e9-11e7-9401-fbc485ff370a.png)
![jira-day](https://user-images.githubusercontent.com/3862495/32427986-7942beb8-c2e9-11e7-8182-5a9f2e5af5b9.png)
![jira-week](https://user-images.githubusercontent.com/3862495/32427987-797de7cc-c2e9-11e7-80a3-7dad3eaa0ab3.png)

Thanks
Suyash

**Comment by suyashjain** [comment]
Hey,

I don't see any action yet...at least add some comment on this.

Thanks
Suyash

**Comment by evernat** [comment]
Please remember, you have not signed any support contract with javamelody and you have not paid a penny for javamelody. It makes a big difference to give support services compared to paid for add-ons such as appfire.
Even if you have not seen many features of javamelody yet, how much would you pay for javamelody add-on per year per server for 100 users?

Anyway, I will answer with the good will I still have.
First, I don't see any bug in this issue and "used memory" is reported as they are in your jvm, with the resolution expected for day and week periods. For example, the first graph is absolutely normal for a server under use, with a GC about each half an hour and without any visible memory problem.
The graph which may show a visible memory leak in your app for this week period is the "crowd_campfire.appfire.com" one. The "used memory" and "%GC" graphs on this server could be monitored on a longer period to confirm a memory leak or if the memory is stabilized after some time.

So closing the issue, since there is no bug to be seen here.
