### ISSUE TITLE
Could be a GC problem with NFS-JavaMelody?

### ISSUE THREAD

**Issue by Zidedine** [javamelody/javamelody#697]
I set the path for store the applications.properties file and the statistics folders in a NFS route. Could be a problem with that?
I use JavaMelody Collector Server with almost 60 applications monitorized. 
In the last days we are getting usually GC (Java Garbage Collector) OutOfMemory errors.

**Comment by evernat** [comment]
I don't think that the storage in NFS could cause GC outofmemory errors.
So to fix these GC errors in the optional collect server, I suggest to configure http-transform-pattern and/or sql-transform-pattern if needed (it would reduce the amount of data to manage in the memory of the collect server).
Otherwise you can increase Xmx.
