### ISSUE TITLE
Internal methods not covered.

### ISSUE THREAD

**Issue by mtulikowski** [javamelody/javamelody#711]
I have an interface which is annotated @MonitoredWithSpring. For this interface I have impl class.
Inside I have a two public methods called by external classes which I can see in Java Melody report.

However one of methods are calling couple of public methods inside the class (which are also present in interface). But none of this method called internally is visible in report. Even if I annotate it with: @MonitoredWithSpring

Some structure picture ;)
<pre>
@MonitoredWithSpring
public interface Foo {
  public void methodA(); //visible in report

  public void methodB(); //visible in report

  @MonitoredWithSpring  
  public void methodA1(); // not visible in report!!!

  @MonitoredWithSpring
  public void methodA2(); // not visible in report!!!
}

public class Bar implements Foo {
  public void methodA() {
    methodA1();
    methodA2();
  }

  public void methodB() {
  }
}
</pre>

**Comment by evernat** [comment]
I think that it's normal, because Spring creates a proxy of the interface. So methods called on the interface are monitored but not methods called on the implementation (for example, calls of private methods in the Bar class are not monitored either).

If you want to monitor methods in the implementation, you can write it like this probably:
```java
public class Bar implements Foo {
  @Autowired
  private Foo myself;

  public void methodA() {
    myself.methodA1();
    myself.methodA2();
  }

  public void methodB() {
  }
}
```
