### ISSUE TITLE
Questions about optional centralized collector server and enhancements

### ISSUE THREAD

**Issue by Zidedine** [javamelody/javamelody#713]
We are using JavaMelody 1.65 in PRO environment. With all applications in Tomcat.

## Questions

**1. We want to make the optional centralized collector server scalable, is it possible?**

Right now we have 60 applications in the centralized collector server. Sometimes, we are having Garbage Collection errors. If we think in have 200 applications, we only see the option of have:
- Tomcat 1 - Centralized collector server 1 [30 applications]
- Tomcat 2 - Centralized collector server 2 [other 30 applications]... and so on. 

**2. To avoid Garbage Collector errors, we are applying transformation patterns to unify requests, what else can we do?.**

Our server configuration is:
-Xmn512m, -Xms1512m, -Xmx1512m, -Xss2048k, -XX:MaxPermSize=512m, -XX:+DisableExplicitGC

We did a heapdump and see that there are a lot of instances in memory of net.bull.javamelody.CounterRequest class. 

We think that 60 applications with a lot of users (>500) for each app in PRO enviroment, is probably too much to handle for only one centralized collector server. That's why we are thinking in scale and have N centralized collector server.

**3. To understand the process: when is a .rrd file created and what represents?** 

We have a lot of files of this type in metrics folder of each app. JavaMelody create one file for every request or sql executed?

20/12/2017 13:14:25 - <FIL> sql669a3e6a1d7379cf9ada8c25c9407a8880da4425.rrd - 33 KB
20/12/2017 13:14:25 - <FIL> sql7eb249e69ada964a6be20f39513f620cceea7c9e.rrd - 33 KB
20/12/2017 13:14:24 - <FIL> sql6ea439afa2d5aca3bf75c465497ef7e1c9f37e1b.rrd - 33 KB
20/12/2017 13:14:23 - <FIL> sql99e65f6d6f3b1f0db22dcce4b686be18ddbed3da.rrd - 33 KB

**4. What effects produces using the parameter javamelody.resolution-seconds?**

We noticed this:

- Smaller rrd files: 33 KB for 60 seconds, 17 KB for 300 seconds.
- The centralized collector server calls, for example, to app_monitorized1/monitoring, app_monitorized_2/monitoring is done each resolution-seconds.
- So, beetween calls...app_monitorized1 and app_monitorized2 are storing statistics in memory until the centralized collector server does the call?

Thank you for this great API.

**Comment by Zidedine** [comment]
**In this time we are having the GC errors**

![heapdump_w_gc_erros](https://user-images.githubusercontent.com/25802371/34247202-e9697eaa-e631-11e7-95b4-ffc6134e6096.PNG)

**Comment by evernat** [comment]
First, sorry for the delay of these answers and I hope that they will help you.
1. Yes, if you really need to scale the collector(s) server(s), you need to have multiple collector server instances with different monitored applications distributed in each of them.

2. In this case (Xmx1512m for 60 applications), you could increase the Xmx (e.g. Xmx3000m), provided that you have enough RAM in the server.
Or you can scale the collector server instances as said in 1.
Or you can check again that you don't have for example 10000 requests in the statistics for a monitored application and several times the same requests except some dynamic values such as identifiers (click the table header in the statistics to order the requests alphabetically to detect almost identical requests). If yes, use http-transform-pattern or sql-transform-pattern. (According to 3 below, you may still have to improve your sql-transform-pattern usage for some applications).

3. If you have a lot of sql*.rrd files for one monitored application (e.g. 10000+ sql*.rrd files), you certainly have to improve your sql-transform-pattern usage in the parameters of that monitored application.
A sql....rrd file is created when there is a new sql requests executed and which is different from the others sql requests. But if the text of the sql request is equals from one execution to the other, then no new sql....rrd file is created (that is there can be N hits for a single sql request with a single sql....rrd file).
For example, for the sql executions below (aka hits), whatever the time when they are executed, there will be 3 requests and 3 sql....rrd files created:
select a from tableX where id = ?
select b from tableY where id = 1
select b from tableY where id = 2
select a from tableX where id = ?
(Note how some sql requests above sadly contains dynamic values 1 and 2, which is a bad practice from the database point of view, and which should be replaced if possible by using sql-transform-pattern in order to have only 2 sql....rrd files instead of 3 and also to have only 2 CounterRequest instances in memory)

4. yes, the resolution-seconds in a collector server does the following as you said:
- Smaller rrd files: 33 KB for 60 seconds, 17 KB for 300 seconds, because there is less data to store for the same periods.
- The centralized collector server calls, for example, to app_monitorized1/monitoring, app_monitorized_2/monitoring is done each resolution-seconds.
- and yes, beetween calls...app_monitorized1 and app_monitorized2 are storing statistics in memory until the centralized collector server does the call. But that's only the delta of statistics since the last call and it's only statistics (mean/max durations, etc) not each single execution/event, so that's not much in memory, at least if sql-transform-pattern is used when needed.

Are the answers ok for you?
