### ISSUE TITLE
Add csrf token to 'View http sessions' page

### ISSUE THREAD

**Issue by oosterholt** [javamelody/javamelody#729]
The 'View http sessions' page exposes all session ids. Therefor this page should also be protected by a csrf token.

**Comment by evernat** [comment]
I suppose that you are speaking of the link 'View http sessions' that display the list of sessions and not of the actions in the sessions page to invalidate http sessions.
(If you were speaking of the latter, then there is already a csrf token, if you have set the javamelody parameter `csrf-protection-enabled=true`).

For the 'View http sessions' link, it is not an action and it does not have any side effect (it only displays a page with the list of sessions to an authorized user). And a link without side effect is by definition not at risk of CSRF attacks. In fact, the attacker could only "force" an authorized user to display the page but the attacker can't get that page for himself.

So the change is not needed and the issue is invalid.
