### ISSUE TITLE
"javamelody init failed" due to regexp

### ISSUE THREAD

**Issue by eetievent** [javamelody/javamelody#739]
Hello,

When configuring this regexp in catalina.properties:
`javamelody.jpa-transform-pattern=(?<=ACTIVITY_ID IN \()[ ,0-9]+\)`

I get:
```
net.bull.javamelody  -   parameter defined: jpa-transform-pattern=(?<=ACTIVITY_ID IN ()[ ,0-9]+)

net.bull.javamelody  -   JavaMelody init failed
```
Antislash are removed because they already used for escaping --> maybe the void parenthesis "()" cause problems.
And then the application doesn't start. Is it normal?

This version with escaped antislashes works fine:
`javamelody.jpa-transform-pattern=(?<=ACTIVITY_ID IN \\()[ ,0-9]+\\)`

It would be interesting to give an example in the documentation, similar to this one (for the double antislash and also to show the lookbehind which is really useful for JavaMelody)
and one example for xml (1 antislash + error using "+": _Regex look-behind without obvious maximum length_):
`<param-value>(?&lt;=ACTIVITY_ID IN \()[ ,0-9]{1,1000}\)</param-value>`

Another point: servlets with one Url only and one parameter to specify an action (for instance http://host/servlet?action=login   ?action=configureAccount    ?action=...) give only one line of statistics. Iit would useful to have an option to tell that the specified parameter defines different request to get one line of statistics for each action (this would work the reverse way of _http-transform-pattern_).

Thank you for developing this great monitoring tool!
Emmanuel

**Comment by evernat** [comment]
> Antislash are removed because they already used for escaping --> maybe the void parenthesis "()" cause problems.
> And then the application doesn't start. Is it normal?
> 
> This version with escaped antislashes works fine

Yes, it is normal. `\` is an escape character in properties files in java. So `\` should be written `\\` in catalina.properties.

> It would be interesting to give an example in the documentation, similar to this one (for the double antislash and also to show the lookbehind which is really useful for JavaMelody)
> and one example for xml (1 antislash + error using "+": Regex look-behind without obvious maximum length)

The [user guide](https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters) was already speaking of lookbehind regexps.
But I have added an example of lookbehind and a note on escaping:

(extract)
The parameter `http-transform-pattern` is a [regular expression](http://java.sun.com/javase/8/docs/api/java/util/regex/Pattern.html) to transform descriptions of http requests and to delete dynamic parts (identifiers of objects for example), in order to aggregate the statistics on these requests irrespective of dynamic parts. This parameter replaces any part of the URL that matches the regular expression with a "$". So setting `http-transform-pattern` to `\d+` means that the URLs "/get/entity/10" and "/get/entity/20" both have their digits matched by the regular expression, and are then aggregated into the URL "/get/entity/$". This also reduces the number of RRD files in the storage directory, as new ones are not created for every id. (You can use lookbehind regexp such as `(?<=entity/)\d+` if necessary. And remember that `<` is escaped as `&lt;` in web.xml and that `\` is escaped as `\\` in catalina.properties.)

Similarly, the parameter `sql-transform-pattern` is a [regular expression](http://java.sun.com/javase/8/docs/api/java/util/regex/Pattern.html) to transform descriptions of sql requests (not binded identifiers for a "in" clause for example) in order to be able to aggregate on these requests.
(/extract)

In your case, I would have written the parameter as
`<param-value>(?&lt;=ACTIVITY_ID IN )\([ ,0-9]+\)</param-value>`
The replacement would have been better in my opinion and you would not have errors about maximum length.
Or `<param-value>\([ ,0-9]+\)</param-value>` would have been more global.


> It would useful to have an option to tell that the specified parameter defines different request to get one line of statistics for each action (this would work the reverse way of http-transform-pattern).

No, this is not planned.

> Thank you for developing this great monitoring tool!

You are welcome.
