### ISSUE TITLE
Update Spring libraries to at least 4.3.18

### ISSUE THREAD

**Issue by jornfranke** [javamelody/javamelody#751]
JavaMelody uses currently Spring 4.3.10 which is nearly one year old. For security reasons and bug fixes it is recommended to update to the latest version (4.3.18) which also includes a lot of updated dependencies.

**Comment by evernat** [comment]
That's wrong. And if a tool says the same as you, then that tool is also wrong or not correctly understood.
In fact, the Spring dependency in javamelody is optional., as you can see in the [pom.xml of javamelody-core](https://github.com/javamelody/javamelody/blob/master/javamelody-core/pom.xml#L207).
Because that dependency is optional and by definition not transitive, javamelody does not use that Spring dependency v4.3 and javamelody will never use that Spring dependency v4.3 and it will only use a Spring dependency vX, if the application in which javamelody is included define a Spring dependency vX.

So javamelody does not use Spring v4.3.10 and there is absolutely no security reason to update that. By the way, the latest version of Spring is 5.0.7 since last week and not 4.3.18 as you said.

**Comment by jornfranke** [comment]
thank you for the quick answer. I proposed 4.3.18 because it was the latest version in the 4.3.x series. 5.x might introduce probably more changes. 

You are correct that it is optional, so what I said does not apply. I overlooked this. 

I thought that the collection server pulled the httpclient library from there which is from 2016

Just a question: Does it make sense to create an issue for updating the dependent libraries in the collection server?

thank you.

**Comment by evernat** [comment]
Yes you may create an issue to upgrade some dependency. Note that httpclient is a transitive dependency of aws-java-sdk-cloudwatch.

But if you want to report a security issue in an open-source project, for a dependency or whatever, please report the security issue in private (evernat _at_ free.fr for javamelody) and not in github public issues. This is needed to have time to analyze, prioritize and fix the issue correctly, without leaving the vigilant users vulnerable.

**Comment by jornfranke** [comment]
Sure, I will do.
