### ISSUE TITLE
Review JIRA configuration with JavaMeldody SQL

### ISSUE THREAD

**Issue by pmcgover** [javamelody/javamelody#758]
We are running JIRA v7.7.1 on prem via Linux VMs with Postgres v.9.3.9.30, PostgreSQL JDBC Driver 42.2.1 and JavaMelody v1.73.1.  We have been using JavaMelody with JIRA for many years and just just added the SQL monitoring option per the [documentation](https://github.com/javamelody/javamelody/wiki/AtlassianPlugin) in our JIRA DEV environment.  We are using Postgres, so I followed this document [How to connect to PostgreSQL using JNDI](https://confluence.atlassian.com/jirakb/how-to-connect-to-postgresql-using-jndi-720418521.html).   The JavaMelody SQL option appears to work well in our "quiet" JIRA DEV environment.  Later we will install in our SIT environment and run it against the JMeter performance testing tool and perform other tests.

Below are my concerns and questions before we consider to promote this change to production:
* Please review the attached file for $DATA/dbconfig.xml and $APPS/server.xml file configurations and let me know if you see any JIRA configuration issues or concerns.
* Are there any performance or configuration concerns with switching from the original jdbc-datasource (which was removed) to the new jndi-datasource for javaMelody?
* Are you aware of any additional performance overhead concerns with adding the SQL Javamelody feature?

Thanks,
Pat
[JIRA-Config-for-JavaMelody-with-SQL-Option.txt](https://github.com/javamelody/javamelody/files/2166934/JIRA-Config-for-JavaMelody-with-SQL-Option.txt)

**Comment by evernat** [comment]
First, you use a datasource, so I don't think that you need jdbc properties outside of the datasource resource (that said, they are no longer inside <jdbc-datasource></jdbc-datasource> so they are not doing anything).
Then you are supposed to use the same jdbc properties in the datasource resource than you were using before, in particular maxTotal.
And finally, when using a recent version of Tomcat you should use in the datasource: maxTotal,  maxWaitMillis and removeAbandonedOnBorrow or removeAbandonedOnMaintenance (and not maxActive, maxWait and removedAbandoned).

So given your file, I suggest to use the following (hostname, username and password obfuscated):
data/dbconfig.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<jira-database-config>
<name>defaultDS</name>
<delegator-name>default</delegator-name>
<database-type>postgres72</database-type>
<schema-name>public</schema-name>
<jndi-datasource>
<jndi-name>java:comp/env/jdbc/jirads</jndi-name>
</jndi-datasource>
</jira-database-config>
```

```xml
<Context path="/jira" docBase="${catalina.home}/atlassian-jira" reloadable="false" useHttpOnly="true">

<!-- The following Resource is for JNDI datasource for JavaMelody SQL -->
<Resource name="jdbc/jirads" auth="Container" type="javax.sql.DataSource"
username="..."
password="..."
driverClassName="org.postgresql.Driver"
url="jdbc:postgresql://...:6445/jira"
connectionProperties=""
maxTotal="50"
maxIdle="20"
maxWaitMillis="30000"
validationQuery="select version();"
removeAbandonedOnMaintenance="true"
removeAbandonedTimeout="300"
logAbandoned="true"
testWhileIdle="true"
timeBetweenEvictionRunsMillis="300000"
minEvictableIdleTimeMillis="60000"
/>

<Resource name="UserTransaction" auth="Container" type="javax.transaction.UserTransaction"
factory="org.objectweb.jotm.UserTransactionFactory" jotm.timeout="60"/>
<Manager pathname=""/>
<JarScanner scanManifest="false"/>
</Context>
```

There are no performance concerns when using a jndi-datasource (otherwise would be surprising given that jndi-datasource is the documented way of [configuring jdbc in Tomcat](https://tomcat.apache.org/tomcat-8.5-doc/jndi-datasource-examples-howto.html)).

And there are no noticeable performance overhead when using the SQL javamelody feature.

**Comment by pmcgover** [comment]
Thanks!  I will try your suggestions.
