### ISSUE TITLE
monitoring page stuck if datasource out of connections

### ISSUE THREAD

**Issue by maxxedev** [javamelody/javamelody#765]
MonitoringController tries to `buildDataBaseVersion()` via `JavaInformations` by checking out a connection from sql datasource.

If however the datasouce conection pool is exhausted and therefore must wait for a new connection, `/monitoring` page is stuck!

Suggested solutions:
Allow db version to be specified through properties
Obtain and cache db version once a datasource is registered to javamelody
Put a timeout on getting a connection (async thread and timeout)

**Comment by evernat** [comment]
First, if your datasource connection pool is exhausted, then you have a big problem for your application (javamelody graph of opened connections can help to prevent or to analyze post mortem such a situation, together with the report of opened connections in "System actions" ).

Then, perhaps javamelody could workaround the situation, in order to display the monitoring page anyway when this is the case. But possible workarounds seem awkward: get connection and cache of db version may slow down server startup and also connections may not be ready at that moment, while async thread is a bit heavy as a workaround.

In my opinion, you should fix pool exhaustion and use timeout in datasource connection pool in case it happens again (the datasource timeout is maxWaitMillis in Tomcat's recent versions).
That way, there is no problem for your app and no problem for the javamelody monitoring page.
And this issue is won't fix for the moment, but thanks for letting us know the situation.
