### ISSUE TITLE
Send Jenkins monitoring stats to DataDog (docs needed?)

### ISSUE THREAD

**Issue by Petezah** [javamelody/javamelody#770]
I see it is possible to send monitoring data to DataDog.  I am also able to use JavaMelody to collect data on my Jenkins instance (through the Jenkins plugin).  Is it possible to combine the two?  How would I go about setting the DataDog API key for the JavaMelody Jenkins plugin (assuming all the codepaths exist in the Plugin version of JavaMelody)?

Edit: It seems like I can accomplish this by passing -Djavamelody.datadog-api-key=FOO to the Jenkins startup command, but since commandline parameters on processes are logged to DataDog, this doesn't seem secure (since I am essentially exposing my API key to anyone who can look at logs in DataDog).

**Comment by evernat** [comment]
Yes you can send monitoring data to DataDog from Jenkins with the parameter `javamelody.datadog-api-key` like you have done.
And because Jenkins is in general started with the embedded winstone/jetty server, you can probably not write javamelody parameters in something like the Tomcat context xml file or the Tomcat's catalina.properties.
In this case, yes you can add javamelody parameters in the Jenkins command line like you have done:
- /etc/default/jenkins: location for most of the Linux distributions.
- /etc/sysconfig/jenkins: location for RedHat/CentOS distribution.
- C:\Program Files\Jenkins\jenkins.xml: default location for Windows.

But indeed, this is not secure if command line parameters are in DataDog logs.
In this case, I think that you can create a file `$JENKINS_HOME/init.groovy.d/javamelody-datadog.groovy` containing:
```groovy
System.setProperty("javamelody.datadog-api-key", "FOO")
```
You will have to restart Jenkins after that.
Reference: https://wiki.jenkins.io/display/JENKINS/Post-initialization+script
The admin page of Jenkins will still display the api key but only if you are Jenkins admin and at least it will not be in the DataDog logs.

Let us know if it works.

**Comment by evernat** [comment]
I really hope that the groovy script is not too late in the startup, but I am not sure of that.

**Comment by Petezah** [comment]
Thanks for replying!  I did try the init.groovy.d script idea.  Bad news though: it looks like it happens *after* all the plugins are already initialized and getMetricsCollectors is already called.  :(  Maybe I'll have to turn off DataDog process collecting on the host, or figure out if I can stop collecting command line parameter info.

**Comment by Petezah** [comment]
An update: I discovered an option to scrub the API key from the logs the datadog agent is submitting.  This seems to be working, and is an acceptable workaround.  It would be cool to have it as an option to add the key in the Jenkins config, but as long as I can scrub it from the data, it will work.  Thanks again! :)

**Comment by evernat** [comment]
Ok, thanks. There is no plan yet to add parameters in Jenkins config (unless you want to do it), but it's great to know that there is an option to scrub it from the logs the datadog agent is submitting.
