### ISSUE TITLE
Execution Plan covering Multiple Connection Pools

### ISSUE THREAD

**Issue by jdesmet** [javamelody/javamelody#771]
When I setup multiple connection pools to different database within tomee, it appears as if java melody uses a random connection pool to run a explain plan against a query, not the original connection pool the query was running against. For Oracle, this leads to "java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist"

**Comment by evernat** [comment]
When having multiple datasources, the explain plan does not use a random one. It uses only the first one in the list.

You may define the order of datasources to have the main one be the first in the list and so to make the explain plan (and the database reports) work most of the time for what you need. To do that, add the javamelody parameter `datasources`. For example, using a system property: `-Djavamelody.datasources=java:comp/env/jdbc/MainDataSource,java:comp/env/SecondaryDataSource`

Given that the explain plan feature is only implemented for Oracle databases and that using multiple Oracle databases in one application is not common and that there is a workaround given above, this issue is won't fix at the moment.
Sorry.
