### ISSUE TITLE
Problem getting stats for jdbc and sql with Oracle database on tomcat 8.5.x

### ISSUE THREAD

**Issue by slaurencelle** [javamelody/javamelody#772]
Hello,

i'm trying to get the stat for jdbc and sql with JaveMelofy install on linux with Tomcat 8.5 running my Java Apps. But i get all the stat but not those one. Do i need to configure or add line to be able to do it.

Thanks for yours help

regards,

stephane

**Comment by evernat** [comment]
See documentation here:
https://github.com/javamelody/javamelody/wiki/UserGuide#7-jdbc

**Comment by slaurencelle** [comment]
Hello i check that but the exemple is for mysql, what are the info i needd to put for Oracle Database which is my case ?


regards,

Stephane

**Comment by evernat** [comment]
If you use a datasource there is no difference between Oracle and mysql.
If you don't use a datasource the difference between Oracle and mysql is that you need an Oracle jdbc driver and an Oracle jdbc url instead of mysql jdbc driver and mysql jdbc url. Is that surprising?

See https://github.com/javamelody/javamelody/wiki/UserGuide#7-jdbc
