### ISSUE TITLE
How to make javamelody capture stat with Oracle database in the back

### ISSUE THREAD

**Issue by slaurencelle** [javamelody/javamelody#775]
Hello,

i like to know how to make javamelody capture the stat for my oracle database and my Java apps ?

i read the documentation but all the exemple is with mysql, so can you give me the string i need to implement and where do i put it.

Regards,

stephane

**Comment by evernat** [comment]
If you use a datasource there is no difference between Oracle and mysql.
If you don't use a datasource the difference between Oracle and mysql is that you need an Oracle jdbc driver and an Oracle jdbc url instead of mysql jdbc driver and mysql jdbc url. Is that surprising?

See https://github.com/javamelody/javamelody/wiki/UserGuide#7-jdbc

**Comment by slaurencelle** [comment]
Hello, 
i knew that but my problem is with the same Java environment but on another server i'm not able to capture the http and jdbc or sql stat and i implement Javamelody the same way on each server.

Stephane
