### ISSUE TITLE
select range statistics

### ISSUE THREAD

**Issue by leccyril** [javamelody/javamelody#783]
HI, 

great tools. but as it as been created for production environment. Is there any chance to configurer the time for stat  ? for example rotation every day or week ? 

1.  we can only purge when server is down. But often in production we can't shut down server

2. it take some place on disk maybe if we can specify rotation every X time it would be wonderful, often we want stat only on day, hour, maybe week.... it would be great to configure this? indeed we can put it with no fear ! (when we have EAR with 10 war and 1 cluster with 4 jvm it will be complicated)

thanks !

**Comment by evernat** [comment]
First, just to be sure, if what you want is to view the graphs and statistics for a period of a day, a week, a month or between custom dates, then choose the period you want at the top of the monitoring page.

Second, if what you want is to reduce the size of files on disk then:
- be sure not to have dynamic values in your http and sql requests (`/people/123` for example) and if you do have dynamic values, use the `http-transform-pattern` and/or `sql-transform-pattern` parameters, in order to aggregate those requests between them.
- Then do not think like other monitoring services which limit you to 1 hour or 1 day or even 1 week worth of data, because to have meaningfull statistics and comparisons, you will need much more than 1 day. 
- And you don't have to specify rotation time which is already automatic: because a RRD file (round robin database) will keep its initial size forever and values in it will be automatically aggregated then purged and also because files will be automatically deleted (after 90 days for graphs no longer used, after 365 days for stats). That way, size of files on disk are typically between 10 and 100 MB.
- if you really want to delete file sooner than 90 and 365, you can use the parameters `obsolete-graphs-days` and `obsolete-stats-days`
- and if you optionally want to aggregate graphs and statistics from an application in a cluster see #785
