### ISSUE TITLE
Multiple servers in a Wildfly server groups put collected data files to same place

### ISSUE THREAD

**Issue by leccyril** [javamelody/javamelody#785]
HI, 

we have 3 applications (app1/app2/app3) in cluster (server1/server2) with 2 jvms (8080/8180) in each node

for example  

http://server1:8080/app1
http://server1:8080/app2
http://server1:8080/app3

http://server1:8180/app1
http://server1:8180/app2
http://server1:8180/app3

http://server2:8080/app1
http://server2:8080/app2
http://server2:8080/app3

http://server2:8180/app1
http://server2:8180/app2
http://server2:8180/app3

We can't override the path to record datas, what it is possible in web.xml set app1/app2/app3 in storage path but on same server app1 on port 8080 and 8081 will take same files

the -D option is not a valuable option, because we can specify by jvm specific parameters, but if we put 

"-Djavamelody.storage-directory=/tmp/javamelody_my_instance" as ticket 

#692 mentionned

it will override app1 with app2  or app2 with app3 .... in each case it will cause issue

overwrite file is not good how we can monitor each app in each JVM ? 

thank for your great tools

**Comment by evernat** [comment]
Yes, you can't write to the same data files from 2 application instances.

But you can override the default storage directory, for example when having two servers 8080 and 8180 with the same apps. Set the parameter `-Djavamelody.storage-directory=/tmp/javamelody_8080` and `-Djavamelody.storage-directory=/tmp/javamelody_8180` for example, then javamelody will create subdirectories for app1, app2 and app3 so it will not write to the same files.

Or, if you want to aggregate all graphs and statistics for the 4 app1 intances (server1:8080, server1:8180, server2:8080, server:8180), you can optionally use the [javamelody collect server](https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#optional-centralization-server-setup).
By adding in the javamelody server, a single application "app1" with 4 instances, you will have only 1 data directory for the app1 files instead of 4 directory and also a single aggregated report for the app1 instances instead of 4 reports.

And idem for app2 and app3.

**Comment by leccyril** [comment]
can i do both,  override in stat files and use collection wrapper ?

**Comment by leccyril** [comment]
and how to configure collector simply?
