### ISSUE TITLE
Session Count Tomcat Cluster

### ISSUE THREAD

**Issue by Vespucci75fr** [javamelody/javamelody#795]
Hi,

First I want to say that I love javamelody... Thanks for this great project.

I recently put my **Tomcat servers in cluster** (Tomcat 9.0.12) with "org.apache.catalina.ha.session.DeltaManager" enabled and a jvmRoute to have sticky connexion on the AJP load-balancer.

I am using the spring framework to help me developing my war.

So on my tomcats I have session with ID _**_EC135D2DB8E2B8797A62D6716D682FE8.server1_**_ This session type is primary on **server1** and backup on **server2**.

The problem is that in 

- **System Information** the **Nb of http sessions** = 2 x real number of sessions
- **System Information** the **View http sessions** show me the correct number of sessions and their details

See attached illustration:

- Nb of http sessions

![nb of sessions](https://user-images.githubusercontent.com/6206228/48770569-afa79a80-ecb6-11e8-9cf4-6ddc0d3a4ae8.png)

- View http sessions

![session list](https://user-images.githubusercontent.com/6206228/48770565-a9192300-ecb6-11e8-91dd-a89cd46bf9a8.png)

Thanks.

**Comment by evernat** [comment]
The http sessions view is based on a map with session id as key. So if there are two session created events for the same session id, then there will only session displayed in the list.
Whereas the http sessions count is [based on a faster counter](https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/SessionListener.java#L130) and not on the size of the sessions map. So the count is implemented like if it was `nb of session created events - nb of session destroyed event + nb of session activated events - nb of session passivated events`.
So the http sessions count may be higher than the number of http sessions in the list, when there is a problem in the session events.

And when I see the [DeltaManager source](http://svn.apache.org/viewvc/tomcat/trunk/java/org/apache/catalina/ha/session/DeltaManager.java?view=markup#l626):

```java
                // FIXME How inform other session id cache like SingleSignOn
                // increment sessionCounter to correct stats report
                if (findSession(session.getIdInternal()) == null ) {
                    sessionCounter++;
                } else {
                    sessionReplaceCounter++;
                    // FIXME better is to grap this sessions again !
                    if (log.isWarnEnabled()) {
                        log.warn(sm.getString("deltaManager.loading.existing.session",
                                session.getIdInternal()));
                    }
                }
                add(session);
                if (notifySessionListenersOnReplication) {
                    session.tellNew();
                }
```

I am not confident on FIXME and warn logs and also on that logic to correctly notify events:
```
if (sessionId unknown)
      count session created
else
      count session replaced

if (notifySessionListenersOnReplication, whatever session created or replaced)
      notify listeners
```

So I suggest to add a http session listener in your webapp and to report back with logs, in order to better understand what are the session events in your cluster with sessions replication:
```java
import javax.servlet.annotation.WebListener;
import javax.servlet.http.HttpSessionActivationListener;
import javax.servlet.http.HttpSessionEvent;
import javax.servlet.http.HttpSessionListener;

@WebListener
public class LogHttpSessionListener implements HttpSessionListener, HttpSessionActivationListener {

	@Override
	public void sessionCreated(HttpSessionEvent se) {
		System.out.println("issue 795, sessionCreated, sessionId=" + se.getSession().getId());
	}

	@Override
	public void sessionDestroyed(HttpSessionEvent se) {
		System.out.println("issue 795, sessionDestroyed, sessionId=" + se.getSession().getId());
	}

	@Override
	public void sessionDidActivate(HttpSessionEvent se) {
		System.out.println("issue 795, sessionDidActivate, sessionId=" + se.getSession().getId());
	}

	@Override
	public void sessionWillPassivate(HttpSessionEvent se) {
		System.out.println("issue 795, sessionWillPassivate, sessionId=" + se.getSession().getId());
	}
}
```

and/or you may try to configure notifySessionListenersOnReplication in the DeltaManager in Tomcat:
```xml
          <Manager className="org.apache.catalina.ha.session.DeltaManager"
                   notifySessionListenersOnReplication="false" ... />
```
but I don't know if there are consequences on the cluster or on your application.

**Comment by evernat** [comment]
Any news? Do you have logs as said above?

**Comment by evernat** [comment]
Finally, I have made some tests. Before the fix, some notes to myself.
First, let's say that we have a webapp with the following listener (which is in a dependency and which is not supposed to know if it is in a Tomcat cluster or not):

```java
import java.io.Serializable;
import java.util.concurrent.atomic.AtomicInteger;
import javax.servlet.annotation.WebListener;
import javax.servlet.http.HttpSessionActivationListener;
import javax.servlet.http.HttpSessionEvent;
import javax.servlet.http.HttpSessionListener;

@WebListener
public class LogSessionListener implements HttpSessionListener, HttpSessionActivationListener, Serializable {
   private static AtomicInteger SESSION_COUNT = new AtomicInteger();
   private static final String ACTIVATION_KEY = "LogSessionListener.activation";

   @Override
   public void sessionCreated(HttpSessionEvent se) {
      System.out.println("sessionCreated, sessionId=" + se.getSession().getId());
      if (se.getSession().getAttribute(ACTIVATION_KEY) == null) {
         se.getSession().setAttribute(ACTIVATION_KEY, this);
         SESSION_COUNT.incrementAndGet();
      }
   }
   @Override
   public void sessionDestroyed(HttpSessionEvent se) {
      System.out.println("sessionDestroyed, sessionId=" + se.getSession().getId());
      SESSION_COUNT.decrementAndGet();
   }
   @Override
   public void sessionDidActivate(HttpSessionEvent se) {
      System.out.println("sessionDidActivate, sessionId=" + se.getSession().getId());
      SESSION_COUNT.incrementAndGet();
   }
   @Override
   public void sessionWillPassivate(HttpSessionEvent se) {
      System.out.println("sessionWillPassivate, sessionId=" + se.getSession().getId());
      SESSION_COUNT.decrementAndGet();
   }
   public static void logSessionCount() {
      System.out.println(SESSION_COUNT.get());
   }
}
```

And the webapp also has a WEB-INF/web.xml to make it distributable:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<web-app xmlns="http://java.sun.com/xml/ns/j2ee" version="2.4"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd">
	<distributable />
	<listener>
		<listener-class>LogSessionListener</listener-class>
	</listener>
</web-app>
```

When using the webapp in a not-clustered Tomcat, we have the following session events:
- Start Tomcat with the webapp and create a session using following jsp:
```jsp
<%@ page session="true" %>
<%= "Session " + (request.getSession().isNew() ? "created" : "already exists") %>
```
- sessionCreated event is printed
- Stop Tomcat
- Start Tomcat
- sessionDidActivate event is printed when session is restored

Session count is one.
So far, so good.


But when using the webapp in a clustered Tomcat (using the default `<Cluster className="org.apache.catalina.ha.tcp.SimpleTcpCluster"/>`), we have the following session events:
- Start Tomcat 1 with the webapp
- Start Tomcat 2 with the same webapp
- create a session in whatever Tomcat
- sessionCreated event is printed in both Tomcats, and not sessionDidActivate
- Stop Tomcat 2 (which Tomcat changes nothing)
- Start Tomcat 2
- sessionDidActivate event is printed in Tomcat 2 when session is received from the other Tomcat for sync
- sessionCreated event is also printed in Tomcat 2, just after sessionDidActivate

Fortunately we could test in the sessionCreated method if the session activation listener is null or not (not null but not == this because of deserialization) in the session. And in the later case ignore it because that's the same session as in sessionDidActivate.
And so session count is also one.

See also:
- [Tomcat's issue](https://bz.apache.org/bugzilla/show_bug.cgi?id=35916), but the Tomcat's user did not ask to notify both sessionDidActivate and sessionCreated.
- [call to activate()](http://svn.apache.org/viewvc/tomcat/trunk/java/org/apache/catalina/ha/session/DeltaSession.java?view=markup#l777
) in DeltaSession.doReadObject(ObjectInput):
- call to [session.tellNew()](http://svn.apache.org/viewvc/tomcat/trunk/java/org/apache/catalina/ha/session/DeltaManager.java?view=markup#l640) in DeltaManager.deserializeSessions(byte[]):

**Comment by Vespucci75fr** [comment]
Thanks so much for this I'll confirm if it fixes my issue... 

It was busy in the last few months at work, sorry if I didn't reply to your previous post.
