### ISSUE TITLE
Display name for dynamically created beans?

### ISSUE THREAD

**Issue by Maczaj** [javamelody/javamelody#798]
Hello,
consider bean that is created dynamically at runtime, for example FeignClients:
```
@FeignClient(...)
public interface MyResource
```

In this case bean name is something like:

> $Proxy200

As a result, monitoring page displays hits in rather not very convenient way such as:

> $Proxy200.myMethod

This is how I've configured advisor:
```    
    @Bean
    public MonitoringSpringAdvisor monitoringFeignClientAdvisor() {
        return new MonitoringSpringAdvisor(new AnnotationMatchingPointcut(FeignClient.class, true));
    }
```
Is there a way to force more readable entries? It would be nice to have entries like 
> MyResource.myMethod

Environment:
> Javamelody 1.74.0
> Spring-boot 1.5.12.RELEASE
> Spring 4.3.16.RELEASE

![image](https://user-images.githubusercontent.com/4427352/49082682-b439f900-f24a-11e8-90a8-140d9eb27d54.png)

**Comment by evernat** [comment]
The class name which you see in the spring statistics is given by org.springframework.aop.support.AopUtils.getTargetClass(methodInvocation.getThis()).getSimpleName()
and for whatever reason it is like $Proxy200.

I suggest to do at your choice:
- either add `@net.bull.javamelody.MonitoredWithSpring(name = "MyResourceNumber1")` on the FeignClient interface(s) and you may also use the following advisor instead of yours above:
```java
    @Bean
    public MonitoringSpringAdvisor monitoringSpringAdvisor() {
        return new MonitoringSpringAdvisor(new MonitoredWithAnnotationPointcut());
    }
```
- or use the following advisor (without adding the MonitoredWithSpring annotation):
```java
    @Bean
    public MonitoringSpringAdvisor monitoringFeignClientAdvisor() {
        MonitoringSpringAdvisor advisor = new MonitoringSpringAdvisor(new AnnotationMatchingPointcut(FeignClient.class, true));
        advisor.setAdvice(new MonitoringSpringInterceptor() {
            @Override
            protected String getRequestName(MethodInvocation invocation) {
                //Class<?> targetClass = AopUtils.getTargetClass(invocation.getThis());
                Class<?> declaringClass = invocation.getMethod().getDeclaringClass();
                String classPart = declaringClass.getSimpleName();
                String methodPart = invocation.getMethod().getName();
                return classPart + '.' + methodPart;
            }
        });
        return advisor;
    }
```

**Comment by Maczaj** [comment]
@evernat thanks for the reply, solution with setting advice did the trick :)

**Comment by evernat** [comment]
Note that `javamelody.advisor-auto-proxy-creator-enabled` should be set to `false` in the application properties of your webapp, in order to disable Spring's DefaultAdvisorAutoProxyCreator. Otherwise executions on feign clients are counted twice.

And the next release of the javamelody spring-boot starter (1.76) will automatically include the monitoring of feign clients, if `javamelody.advisor-auto-proxy-creator-enabled` is set to `false` in the application properties. See 0af308b
Compared to the solution above, it adds the path and http method in the request name. For example:
```
/stores/{storeId} POST
StoreClient.update
```

**Comment by evernat** [comment]
Finally, you will not have to set `javamelody.advisor-auto-proxy-creator-enabled` to false, because it will be false by default in 1.76 (21d904d).
