### ISSUE TITLE
Garbage Collection difference Melody chart / GC logs

### ISSUE THREAD

**Issue by timguy** [javamelody/javamelody#812]
Hi,
maybe I missunderstand some concepts but I have different charts when I watch into 
* Java Melody - Garbage Collector Time
* garbage collection files (uploaded and chart by https://gceasy.io)

I miss the 210 seconds peak in the Java Melody chart.

I am using the java melody jenkins plugin. 

![grafik](https://user-images.githubusercontent.com/14115943/52714787-162d1380-2f9b-11e9-99f1-e100d5ee0608.png)

![grafik](https://user-images.githubusercontent.com/14115943/52714675-cf3f1e00-2f9a-11e9-8649-07a1759e930d.png)

**Comment by evernat** [comment]
You should note that GC logs have higher resolution and GC logs have data stored for minor GC and full GC, while the javamelody graph has by default a value by minute which is a percentage of cpus time.
So, while GC logs store a lot of data, GC logs are a good tool when you have a GC problem, as a complementary tool to javamelody. In fact, it would be good if javamelody could display itself graph from GC logs when they are available (that's a feature already written in the TODO list).

In this case, the javamelody graph for GC shows that GC has increased from the start of the graph up to 19h but it does not show the full GC at about 20h. Sorry.
The full GC value may have been excluded because of too much missing data around that time because "full GC stops the world" and the full GC pause was too long (210s) compared to missing values and the XFF (X-Files factor) in the RRD graph (Round Robin Database).

That said, if you really have problems with full GC, you may mitigate the issue by using JDK 10 or JDK 11, which uses parallel full GC (on all cores) instead of single-threaded full GC (on one core) in JDK 9 and before. (For Jenkins, see https://jenkins.io/doc/administration/requirements/java/). Of course, you may also try to find and fix the full GC problem (if configuration is not enough, that may not be easy in your case if your are not a developer of Jenkins).

**Comment by timguy** [comment]
@evernat thanks for the fast and extensive comment. Well, will continue tinkering with gc settings ;-).
