### ISSUE TITLE
Thousands of sql*.rrd and http*.rrd files

### ISSUE THREAD

**Issue by arve0** [javamelody/javamelody#815]
**Question**

What is the preferred method for cleaning up sql*.rrd files?

---

**Environment**

JavaMelody version 1.26.0
Weblogic version 12.2.1.2.0
Red Hat Enterprise Linux Server release 6.10 (Santiago)

---

**Problem description**

Java Meldoy generates thousands of sql- and http(hash).rrd files in storage-directory.

Expected: Java Melody should clean temporary files.

---

**Detailed description**

Example files:

```sh
$ ls -lt
...
-rw-r--r--+ 1 weblogic weblogic   34272 Nov 24 16:00 http194239916c05aa945d828c37355c883390d23a26.rrd
-rw-r--r--+ 1 weblogic weblogic   34272 Nov 24 16:00 httpd83c4a1c2edd050ed5a112393dca9bc9213f49ac.rrd
-rw-r--r--+ 1 weblogic weblogic   34272 Nov 24 16:00 http95e7270fef462f8f79f155b13cd5b85b0cf63c30.rrd
-rw-r--r--+ 1 weblogic weblogic   34272 Nov 24 16:00 http1658694fc1038d4e83e54831403ec2dbd7f9ee40.rrd
-rw-r--r--+ 1 weblogic weblogic   34272 Nov 24 16:00 http844fb846d1813bf6e2017f1ef4350bfe68699e3d.rrd
-rw-r--r--+ 1 weblogic weblogic   34272 Nov 24 16:00 http8ef43b65cec3c88135b55af54acaf7d304a6164f.rrd
-rw-r--r--+ 1 weblogic weblogic   34272 Nov 24 15:59 sqldfef2e8efe8eed9f2825f96c2d496baf2c481717.rrd
-rw-r--r--+ 1 weblogic weblogic   34272 Nov 24 15:59 sqld98aa32d18e8efa551d237b82726e2f6f423f025.rrd
-rw-r--r--+ 1 weblogic weblogic   34272 Nov 24 15:59 sqlfd10e70889b5fc3255451e14c908b5b267e92e33.rrd
-rw-r--r--+ 1 weblogic weblogic   34272 Nov 24 15:57 sqlc8308325f577ba0aa1c95989588a51dc53ea0278.rrd
-rw-r-xr--+ 1 weblogic weblogic   34272 Nov 24 15:48 sql7e7bcf202c5e73427d3cbc508210953a20a5558c.rrd
...
```

Files are created in heaps
```sh
$ ls -lt | grep "Nov 24 15:55" | wc -l
0
$ ls -lt | grep "Nov 24 15:56" | wc -l
0
$ ls -lt | grep "Nov 24 15:57" | wc -l
1
$ ls -lt | grep "Nov 24 15:58" | wc -l
0
$ ls -lt | grep "Nov 24 15:59" | wc -l
3
$ ls -lt | grep "Nov 24 16:00" | wc -l
24
$ ls -lt | grep "Nov 24 16:01" | wc -l
58
$ ls -lt | grep "Nov 24 16:02" | wc -l
1
$ ls -lt | grep "Nov 24 16:03" | wc -l
0
```

...and are not updated:
```sh
$ stat httpeadca92e74b4cf36bbd7a5bc2fd98d25da2097dc.rrd
  File: `httpeadca92e74b4cf36bbd7a5bc2fd98d25da2097dc.rrd'
  Size: 34272           Blocks: 72         IO Block: 4096   regular file
Device: fd04h/64772d    Inode: 171702      Links: 1
Access: (0644/-rw-r--r--)  Uid: (  503/weblogic)   Gid: (  503/weblogic)
Access: 2018-11-10 14:00:23.482098024 +0100
Modify: 2018-11-10 14:00:23.482098024 +0100
Change: 2018-11-10 14:00:23.482098024 +0100
```

In majority (~95%), the files consume exactly 34272 bytes:

```sh
$ ls -lt | wc -l
67424
$ ls -lt | grep 34272 | wc -l
63976
```

In total, the files consume a lot of space:
```sh
$ du -h
3.1G    .
```

Seemingly, I can remove the files without messing the graphs at the web frontend.

**Comment by evernat** [comment]
Are you sure about javamelody version 1.26.0? That would be 8 years ago and current version is 1.76.0.

First, yes you can remove the sql*.rrd and http*.rrd files yourself without issues or JavaMelody will automatically delete the unused rrd files after 90 days by default, which seems to be too late for you.

But, it seems that you have so many thousands sql*.rrd files (more than 10000) because there are dynamic values such as identifiers in your sql queries, instead of using [jdbc bind parameters](https://use-the-index-luke.com/sql/where-clause/bind-parameters).

Of course, you could fix your code to use bind parameters.

And otherwise, you are supposed to tell javamelody what are the dynamic values in your sql queries which should be aggregated, by using the sql-transform-pattern parameter. An example of sql-transform-pattern regexp covering many cases like hard-coded numbers, strings, and also dynamic "in" criteria could be:
   `\d+|\'.+\'|\([\?, \d]+\)`
You can set the parameter in web.xml or using a system property for example:
`-Djavamelody.sql-transform-pattern=\d+|\'.+\'|\([\?, \d]+\)`
It will reduce the number of sql*.rrd files but it will also reduce the many IO on disk and it will reduce a bit the memory used by javamelody.

And you may also have many thousands http*.rrd files if there are dynamic values in URLs like in `/book/show/23`. Likewise in this case, you should use a regexp in http-transform-pattern, for example:
`-Djavamelody.http-transform-pattern=\d+`

Doc: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters

Otherwise, as a last resort, you could use the parameter obsolete-graphs-days (90 by default) to automatically delete rrd files which are unused for more than X days. For example, the system property `-Djavamelody.obsolete-graphs-days=15` will have more or less the same effect than if you delete sql*.rrd and http*.rrd files older than 15 days every midnight.

**Comment by arve0** [comment]
> Are you sure about javamelody version 1.26.0? That would be 8 years ago and current version is 1.76.0.

Heh, yes 😅

> But, it seems that you have so many thousands sql*.rrd files (more than 10000) because there are dynamic values such as identifiers in your sql queries, instead of using [jdbc bind parameters](https://use-the-index-luke.com/sql/where-clause/bind-parameters).
>
> Of course, you could fix your code to use bind parameters.

You are correct. Thanks for your quick response, the pointers and your time. :octocat:
