### ISSUE TITLE
Treatment of proxy datasources when wrapping.

### ISSUE THREAD

**Issue by howorang** [javamelody/javamelody#824]
I have some datasources of type: org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy defined in the Spring project. Default configuration picks up every defined datasource along with the proxies. Should i exclude some of them if so which ones?

**Comment by evernat** [comment]
You could exclude some datasources and I think it would be better to exclude the LazyConnectionDataSourceProxy ones.
(For that, if you use spring boot and the javamelody spring boot starter, then add in your application.yml: `javamelody.excluded-datasources: ...` with the bean names of the datasources to exclude, as a comma separated list. Or if you import net/bull/javamelody/monitoring-spring.xml in your spring context, then copy the content of the [net/bull/javamelody/monitoring-spring.xml](https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/resources/net/bull/javamelody/monitoring-spring.xml) and import your own version instead, after changing the excludedDatasources part.)

But excluding some datasources should not change anything in the number of "hits" in the sql statistics of the reports, because javamelody does not wrap jdbc connections twice anyway.

**Comment by evernat** [comment]
Sorry, after thinking of what LazyConnectionDataSourceProxy means, I see that it also creates proxy of jdbc connection and only of Connection interface, so javamelody can't see that jdbc connections are monitored twice making sql hits probably doubled.
So yes, you should exclude LazyConnectionDataSourceProxy ones.

**Comment by evernat** [comment]
And for the next release (1.77), I have committed a fix to automatically exclude LazyConnectionDataSourceProxy if the target datasource is already monitored.
A snapshot build is available at:
javamelody.org/downloads/javamelody-core-1.77.0-SNAPSHOT.jar

**Comment by howorang** [comment]
Thank you for answering.
