### ISSUE TITLE
JCacheInformations starts Ignite instance

### ISSUE THREAD

**Issue by sergebg** [javamelody/javamelody#858]
JCacheInformations starts Ignite instance. This is not desirable. There should be a way to suppress JCache details collection. This could be done using system properties, servlet context parameters, filter parameters.

**Comment by evernat** [comment]
What JCacheInformations does is `foreach (Caching.getCachingProviders()) call getCacheManager().getCacheNames()` and also it reads jcache MBeans.
I don't think that it is uncommon to do that. And I think that doing that should be ok at any time.

You say that JCacheInformations in JCache details collection "starts" Ignite instance.
I don't know what you mean by "starts" Ignite intance, but if you don't want Ignite instance to be started, there should be a way, in Ignite, to disable "starting" instance. And it is certainly possible in Ignite default configuration to do almost nothing. 
Said otherwise, if you include Ignite in your webapp, then you should include Ignite configuration for what you want (that is do nothing), given that Ignite is a JCache api compatible provider. Or if you don't want to "start" Ignite instance ever, the simplest is to remove Ignite from your application.
So closing as won't do.
