### ISSUE TITLE
JobInformations starts Quartz scheduler

### ISSUE THREAD

**Issue by sergebg** [javamelody/javamelody#859]
JobInformations starts Quartz scheduler. In my case I have just to removed quartz dependency. But in general case, details collection should not have such side-effects. If it's not possible to avoid the scheduler initialization, then this should be a way to suppress details collection at all (properties or parameters).

**Comment by evernat** [comment]
You may try [quartz-default-listener-disabled](https://github.com/javamelody/javamelody/wiki/UserGuide#13-batch-jobs-if-quartz) which exists for Spring scheduling.
Otherwise like #858, I don't think that listings declared jobs should be a problem when Quartz is present in the application, including if your webapp never declares jobs.
As you said, if you don't want to "start" Quartz in order to list declared jobs, the simplest and recommended way is to remove Quartz from your application.
So closing as won't do.
