### ISSUE TITLE
sending anonymized stats by default IS NOT OKAY and should be opt-in

### ISSUE THREAD

**Issue by tstack** [javamelody/javamelody#862]
Sending anonymized data with the version check **IS NOT OKAY**!  Especially since it does not seem to be mentioned in the documentation!

https://github.com/javamelody/javamelody/blob/f3139f4c53801f94fc91de00f060ed47196a935d/javamelody-core/src/main/java/net/bull/javamelody/internal/model/UpdateChecker.java#L134

**Comment by evernat** [comment]
It was already explained in the release notes and now it is also explained in the documentation: https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#update-check

You can disable the update check with a javamelody parameter `update-check-disabled` in web.xml, in context or in system properties like the other [javamelody parameters](UserGuide#6-optional-parameters). For example `-Djavamelody.update-check-disabled=true`.

This is anonymized data and not personal data (no hostname, no webapp's name, no webapp's classes).

When having an update check in a software, there is always anonymized data as far as I know. Anonymized data is sent by default, to build global statistics, such as how many applications are still using javamelody with Java 1.6, which helps to know if javamelody should still support Java 1.6 in the next release. Without looking far, this is the same for example in Glassfish, Confluence, JIRA, Jenkins, Ehcache, Quartz scheduler and many others for sure.

**Comment by tstack** [comment]
> When having an update check in a software, there is always anonymized data as far as I know.

If it is supported, it is opt-in by the application, not a default.

> Without looking far, this is the same for example in ... Quartz scheduler

The Quartz scheduler removed the update checker a few years ago:

https://github.com/quartz-scheduler/quartz/commit/e1f78465fae7d3e81d30487f7f47697ec9a30d87

Your project is not so important that you need to know about anyone's systems.  This is ridiculous.

**Comment by defnull** [comment]
> When having an update check in a software, there is always anonymized data as far as I know.

This is not an update check, it is a statistics gathering tool disguised as an update check. The statistics gathered and transmitted are not required to check for updates, and there is no way to opt out of that without also disabling the (questionable useful) update check itself.

Also, the information is transferred unencrypted and contains potentially sensitive information (e.g. database vendor and exact version; os name, version and patch-level; configuration parameter names; hardware limits and more). If you the documentation would actually list and describe all the information that is collected, and made it an opt-in, then nobody in their right mind would activate this 'feature' on a productive system. That alone should be reason enough to not do something like that in the first place. Just because you can do something (and maybe others do it) does not mean you should. 

Please re-open this issue for discussion.

**Comment by evernat** [comment]
> This is not an update check, it is a statistics gathering tool disguised as an update check.

Again, when having an update check in a software, there is always anonymized data as far as I know.
Without looking far, this is the same for example in Glassfish, Confluence, JIRA, Jenkins, Ehcache, ~Quartz scheduler~ Eclipse, Firefox and many, many others. Check for yourself.

This is useful to know anonymized and aggregated stats, for example to know if we should still support Java 1.6 or if we should test with Java 14, or if we should put a lot of efforts into the reports for Postgresql or Ingres instead, according to benefits for the users. Update check is also useful in order to notify users about bugfixes and enhancements which they may need.

For example, the Mozilla foundation is known to respect privacy, at least compared to some other software and services. Yet Mozilla Firefox collects anonymized data by default, yes by default. The page https://data.firefox.com/ gives more information. Here is an extract:

> [...] All data is from a representative 10% sample from our Release, Beta, ESR, and Other channels for Firefox and the report runs once per week. Each datapoint covers a week's worth of data (unless stated otherwise). All data is anonymized and aggregated to ensure user privacy. [...]

As we can see with the same page, Firefox collects its version, os name and version, hardware details, plugins and their versions, including when there are known vulnerabilities. After learning that 43% still have the Flash plugin today according to aggregated stats, I personally have checked in my own Firefox. And it suggests upgrading to latest versions when needed, for example to fix vulnerabilities.

Most Firefox users do not disable that. And I still recommend to use Firefox, which seems better than others. In my opinion, it is also effective to fix vulnerabilities sometimes and so to improve user privacy. We could speak about collected anonymous data in Firefox for hours.

> there is no way to opt out of that without also disabling the (questionable useful) update check itself

That's true. If you want to stay absolutely unknown without any contact, you need to disable update checks in javamelody as explained above (and do the same in others tools) or you may disable the fact that the server/jvm is connected to internet by default.
Since you don't need to sign a commercial license and since javamelody does not send all your monitoring data to any server, unlike well-known and successful SaaS solutions, nobody except you can know that you are using javamelody in this case.

**Comment by tstack** [comment]
> Again, when having an update check in a software, there is always anonymized data as far as I know.
Without looking far, this is the same for example in Glassfish, Confluence, JIRA, Jenkins, Ehcache, Quartz scheduler Eclipse, Firefox and many, many others. Check for yourself.

Oh, okay.  I only checked Quartz at first, but let's check Ehcache.  Let's see what the internet has to say about this update check:

https://stackoverflow.com/questions/2407169/how-to-disable-the-ehcache-update-checker

For everyone's convenience, I'll paste a screenshot of the comments on that question:

![image](https://user-images.githubusercontent.com/107532/65599294-6701e300-df52-11e9-9d9b-caf4df672267.png)

Those comments don't seem very positive...

Now, let's check the code:

https://github.com/ehcache/ehcache3/search?q=updatecheck&unscoped_q=updatecheck

No results.  Well, looks like they removed the update check in the latest version.  So, no, ehcache *does not* do an update check anymore.

Perhaps you should do some due diligence before throwing out evidence you think is in favor of your claims.  Because not only do these two not support your claim.  They actively refute it!

> For example, the Mozilla foundation is known to respect privacy, at least compared to some other software and services. Yet Mozilla Firefox collects anonymized data by default, yes by default.

Firefox is an end user application.  Javamelody is a library.  There is a big difference.  Also, I just happened to upgrade my machine and hadn't downloaded Firefox yet, so I just did it right now.  What happens when you first open Firefox?  It loads the following URL in a new tab:

https://www.mozilla.org/en-US/privacy/firefox/

That page *very clearly* states what they're doing and why.  The javamelody check was happening silently and unexpectedly (because, again, it is a library and not an end-user application).  They also have separate settings for the update check and data collection.

> As we can see with the same page, Firefox collects its version, os name and version,

Because, obviously, in order to download a *native* application, it needs to know these things.  Why does a **JAVA library** need to know this?  It doesn't, plain and simple.

> or you may disable the fact that the server/jvm is connected to internet by default.

That is not a realistic solution!  You are grabbing at straws.

You are so clearly and obviously in the wrong here, stop this nonsense and flip the default.

**Comment by defnull** [comment]
Let's be honest, this data collection serves no purpose other than the curiosity of the author. http://javamelody.org/usage/stats looks nice, there are some pretty graphs and large numbers, but for the actual user of the library there are no benefits, only downsides.

Having the data collection enabled by default with no warning in the logs, and then hiding it behind an "Update Check" that actually does not need any of the collected data to do its job, is a clear sign that the author knows exactly what he/she is doing. @evernat knowingly makes the library worse for its users to gain some personal benefit or ego boost out of it. That is actually the bigger issue here. This library is used in sensitive, cooperate environments. How should we trust the author to not do something even more invasive in the future? Who guarantees that the IPs are not logged along with the data? The server-side data collection code is not open-source, is it?

This is such a small issue with such an easy fix: Document (clearly) what kind of data is collected and why, and make it opt-in. Ask users nicely, and perhaps they will willingly offer you insight into their productive environments. If not, then at least you didn't steal that info from users who trusted you.

**Comment by pointer2array** [comment]
Maybe we should force the user to decide. A mandatory key with no defaults. ( javamelody.update-check-disabled). 

Btw, I found the stats page to be insightful, where else can get such data for Java stack?
