### ISSUE TITLE
Security policy

### ISSUE THREAD

**Issue by cinessa** [javamelody/javamelody#877]
Hi All,

I want to install plugin under production JRA/Confluence server. I see the following message on Atlassian Marketplace: " Atlassian's privacy policy is not applicable to the use of this apps". Are you planning to receive Atlassian  security certification?

Thanks,
Inessa

**Comment by evernat** [comment]
Atlassian's privacy policy is about Atlassian products themselves. It is not about the javamelody monitoring plugin.
There is a privacy policy for the javamelody monitoring plugin: https://github.com/javamelody/javamelody/wiki/AtlassianPlugin#privacy-policy
Based on this privacy policy and other requirements, the javamelody monitoring plugin was [approved by Atlassian, for data center](https://www.atlassian.com/licensing/data-center-approved-apps), except that it can not yet be published as such because of a technical issue in the Atlassian marketplace.
I don't know if this qualifies as "Atlassian security certification".
I am not sure either that Atlassian gives "security certification" for any thirdparty plugins. If you are in France, I can ask a consultant for information about that. (For that, contact me at evernat -at- free.fr.)
Otherwise, is it ok for you?

**Comment by evernat** [comment]
I suppose that it is ok.
