### ISSUE TITLE
Do not use the same storage directory with multiple instances or it will cause data loss. Configure the storage-directory parameter if needed.

### ISSUE THREAD

**Issue by onlylov3y** [javamelody/javamelody#879]
Sorry, I upgrade Javamelody core to 1.80
But have a message coming in the monitoring page: "Do not use the same storage directory with multiple instances or it will cause data loss. Configure the storage-directory parameter if needed."
I changed javamelody storage directory but this problem not resolve.
Could you help me to check this? 
Thank you so much!

**Comment by madawg** [comment]
I also got the same problem. Javamelody upgraded from 1.56  to 1.80.
env: Linux, java1.7

**Comment by evernat** [comment]
This message is a warning to say that you use the same storage directory for the monitoring of 2 webapps from 2 server instances in the same machine or from several machines sharing the same directory. This is not good since the monitoring of the 2 webapps may overwrite the files from each other.
It happens for example if you have 2 webapps using the same context path in 2 server instances on the same machine.

To fix this you should use the `storage-directory` javamelody parameter with different values, in the xml context files if Tomcat or in system properties or in web.xml files of each webapp.
Or you can use the `application-name` javamelody parameter with different values in each webapp.
Look at https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters for the doc to set javamelody parameters.
