### ISSUE TITLE
Diskspace Usage / Delete/Clear Reports

### ISSUE THREAD

**Issue by WIPService** [javamelody/javamelody#892]
Problem 1:
If we start `purge_obsolte_files` - it wont delete as many data as we would expect (what does it do really?) It seems to be depending on `all or week or day` and it seems to depend on every single Webapplication? Is this assumption correct?

Problem 2:
We have many different Webapplications deployed in our Tomcat and their names changes very often. Therefore we have many unused data in <temp> folder as this data wont be deleted on undeploy (as i read in UserGuideAdvanced this seems to be intended?)

So if we undeploy a WebApplication - their data will stay in temp-folder.

Example:
```
webapps/c
webapps/d

temp/a (2 GB)
temp/b (4 GB)
temp/c (1 GB)
temp/d (500 MB)
```

How can we go rid of this data while staying online?

We already use this Option found in #561 
`-Djavamelody.obsolete-graphs-days=90 -Djavamelody.obsolete-stats-days=90`
But this wont work on already undeployed webapps.

Is there any possibility to delete such data on undeploy of a webapp?

Problem 3:
Is it possible to delete such data (temp/a temp/b) from webapps which are no longer existing without stopping our tomcat?

**Comment by evernat** [comment]
1. What "purge obsolete files" does is delete *.gz files of statistics which are obsolete (older than 365 days by default) and delete *.rrd files of graphs which are obsolete (not written to for 90 days by default). It never depends on the choosen period in the report (day, week ...). If you click "Purge obsolete files", yes the purge is only for the webapp of the monitoring report displayed, but you don't need to click on that, because the purge will be automatically called every day at midnight for every monitored webapp, if the webapp is still deployed at midnight of course. 

2. Yes, it is intended that the files storing the monitoring data are not deleted when the webapp is undeployed. Because in general, the name of the webapp does not change or at least not often and so when it is undeployed it is often reployed with a new version and the same name shortly after. That way, the monitoring data is persistent and is not lost when deploying new versions of the webapp or when restarting the server.
Once a webapp is undeployed and not redeployed after that, there is no way in javamelody to delete the monitoring data of the webapp (monitoring data is like waiting for the webapp with the same name to be redeployed). If you really want to do that anyway and to delete all the monitoring data of the webapp (and so lose history) when undeploying the webapp, then you may add a servlet listener in your webapp, like the following (note: javamelody-core jar file is supposed to be in WEB-INF/lib of the webapp):
```java
import java.io.File;
import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import javax.servlet.annotation.WebListener;
import net.bull.javamelody.internal.common.Parameters;

@WebListener
public class DeleteJavamelodyDataServletContextListener implements ServletContextListener {
    public void contextInitialized(ServletContextEvent sce) { }
    public void contextDestroyed(ServletContextEvent sce) {
        final File[] files = Parameters.getStorageDirectory(Parameters.getCurrentApplication())
            .listFiles();
        if (files != null) {
            for (final File file : files) {
                file.delete();
            }
        }
    }
}
```

3. Yes, you can delete by yourself the files from webapps which no longer exists without stopping tomcat. You may even do that on currently deployed and running webapps (you will lose history of course): new files will be created again by javamelody after that.

Another major issue in your case is that the storage directories are not supposed to use 500 MB or 4 GB. They are supposed to use about 100 MB even after months or years of use. You probably have too much sql*.rrd or http*.rrd files in the storage directories. To fix that you should:
1. Execute (in Linux) the following commands to count files and see if you have more sql*.rrd than http*.rrd files (or the opposite):
ls sql*.rrd | wc -l
ls http*.rrd | wc -l
2. Open the monitoring report for the month period and open the Details of sql (or http) statistics. Click on "Request" to sort the table.
3. Find which requests are repeated and differs only by dynamic values such as ids. Add a javamelody parameter `sql-transform-pattern` (or `http-transform-pattern`) with a regexp like `\d+` to match the ids in the requests. So, the requests will be correctly aggregated and will use much less disk space.
For more examples of these parameters, see https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
