### ISSUE TITLE
Is there support for Spark micro framework?

### ISSUE THREAD

**Issue by cehdmoy** [javamelody/javamelody#893]
Hey there, I've used javaMelody with sprinbBoot and everything went good. But I have no clue how to integrate it with spark (http://sparkjava.com/)

Any help would be appreciated.

**Comment by evernat** [comment]
If you have a web.xml containing the SparkFilter in your webapp, then you can add the javamelody MonitoringFilter and SessionListener in web.xml, before the SparkFilter, exactly as said in the [user's guide](https://github.com/javamelody/javamelody/wiki/UserGuide#2-webxml-file).

Otherwise, if you run Spark only by code, you need to add the javamelody servlet filter and listener in your code. See https://stackoverflow.com/questions/32631294/how-can-a-native-servlet-filter-be-used-when-using-spark-web-framework for an example of a servlet filter with Spark using Jetty's FilterHolder.

By the way, Spark is in hibernation. There are very few commits in Spark since October, 2018 and none since May, 2019: https://github.com/perwendel/spark/commits/master
