### ISSUE TITLE
Session not show correctly

### ISSUE THREAD

**Issue by bientt210** [javamelody/javamelody#896]
Hi Everyboby,

My JavaMelody using LDAP/Active Directory authentication, but in HTTP Session, some Username in User collum show EMPTY, i dont know why.

Can someone explain this?

**Comment by evernat** [comment]
Hi,

The username column is displayed in the HTTP Sessions report, because there is at least one user identified by the servlet api (by `HttpServletRequest.getRemoteUser()` in the `MonitoringFilter` in fact), otherwise the Username would not be displayed at all.
It may be yourself using LDAP/Active directory or it may be several users.

And is it displayed "EMPTY" or just nothing with an empty value? I suppose just an empty value now.

If you are the only one identified, then other users may have http sessions but they are not identified by `HttpServletRequest.getRemoteUser()` in the `MonitoringFilter` and they may be identified by another custom mean. If there are several users, then some users may be identified and some others not. For example, depending on your webapp, an http session may be created when they access the webapp and some users may complete login while some others may change their mind without completing login.
