### ISSUE TITLE
Node offline status

### ISSUE THREAD

**Issue by sathish97625** [javamelody/javamelody#899]
Hi, It is not providing Node offline status, can you let me know, how we can get this information when one of the slave nodes go down, thanks.

**Comment by evernat** [comment]
When you use an optional collector server:
-  if the monitored application has a single node, you get an alert at the top of the monitoring report when the node is offline
- if the monitored application has several nodes, you get an alert if all the nodes are offline
- otherwise there are currently no alerts.
But in that last case, you can see that a node is offline when you see a sudden decrease of used memory and cpu at the same time and in the System informations of the monitoring report, you can see that a node is missing.
I think that I will also add an alert in that last case.

**Comment by evernat** [comment]
Alert added in the report of the monitored application by 481da3e
