### ISSUE TITLE
Increased session size on Wildfly 18.0.1.Final

### ISSUE THREAD

**Issue by OBreidenbach** [javamelody/javamelody#900]
When using Javamelody to monitor our application Wildfly 18.0.1.Final, each session uses roughly 300% as much memory as compared to the application without Javamelody.

Analysis showed, that each session references its _com.sun.faces.RequestContextMap_ if the application is monitored by Javamelody. Without monitoring, those references do not exist.

**Steps to reproduce the problem**

We've created a small application just rendering a index.xhtml file.

[wfly-mldy-filter.tar.gz](https://github.com/javamelody/javamelody/files/4293421/wfly-mldy-filter.tar.gz)

**With Javamelody**

- compile and package the application `mvn clean install`
- this will also download wildfly 18.0.1.Final to $HOME/.wfly-mldy-filter/wildfly-18.0.1.Final
- start the application
- create 1000 sessions using Apache Benchmark `ab -n 1000 http://localhost:8080/wfly-mldy-filter`
- a heap dump will show exactly 1000 instances of _com.sun.faces.RequestContextMap_, each referencing its corresponding Request/Response Wrappers
 
**Without Javamelody**

- remove Javamelody from the application by
  - edit pom.xml, remove dependency
  - edit web.xml, remove filter declarations
- compile and package the application `mvn clean install`
- start the application
- create 1000 sessions using Apache Benchmark `ab -n 1000 http://localhost:8080/wfly-mldy-filter`
- heap dump shows just the io.undertow.server.session.InMemorySessionManager$SessionImpl instance, but no reference to any Request/Response wrapper whatsoever.

**Comment by evernat** [comment]
For sure, javamelody does not put `com.sun.faces.RequestContextMap` in session.
So, I will look at that.

**Comment by evernat** [comment]
I have not reproduced the same with `com.sun.faces.RequestContextMap`, but I have reproduced with [io.undertow.servlet.spec.ServletContextImpl](https://github.com/undertow-io/undertow/blob/master/servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java).

In fact:
1. The javamelody SessionListener keeps track of http sessions. It is needed to list them in the reports and for the "invalidate all sessions" action. Nothing in the servlet api says that an http session should not be kept after the request and I think that WildFly actively supports this case.
2. The [http session impl of Undertow](https://github.com/undertow-io/undertow/blob/master/servlet/src/main/java/io/undertow/servlet/spec/HttpSessionImpl.java) keeps a reference on the current request and response when the session was read, since [this commit](https://github.com/undertow-io/undertow/commit/0c0abf223ab2d967cf0a42487b70cb450e8e0bc7).
3. In your case, `com.sun.faces.RequestContextMap` is probably an attribute of this request, put by JSF.

I think that Undertow should not do that and I will probably create a PR soon in Undertow, to suggest a fix for that.

When using WildFly/Undertow, the increased memory kept in http sessions is not more, per session, than one instance of request impl and one instance of response impl from the [ServletRequestContext](https://github.com/undertow-io/undertow/blob/master/servlet/src/main/java/io/undertow/servlet/handlers/ServletRequestContext.java) of Undertow. So that may not be much.

A workaround is to remove the javamelody SessionListener from web.xml and to add `metadata-complete="true"` in web.xml (removing the SessionListener from web.xml is not enough with servlet 3.1). But you will lose the report of http sessions, the "invalidate all sessions" action and the graph of the sessions count.

**Comment by evernat** [comment]
Closed a not a bug.

**Comment by evernat** [comment]
See PR https://github.com/undertow-io/undertow/pull/862

**Comment by OBreidenbach** [comment]
@evernat: We do not need the list of sessions and we do not want to invalidate the sessions through the javamelody frontend. We just want to monitor the session count. 
It would be nice, if it would be possible to monitor the session count without keeping session references in the SessionListener. Any chance you include a config param to change the behavior of SessionListener?
