### ISSUE TITLE
Too much sql error added by addRequestForSystemError method

### ISSUE THREAD

**Issue by mymilkbottles** [javamelody/javamelody#902]
![image](https://user-images.githubusercontent.com/19325380/76518797-ba350700-649a-11ea-8d5c-54a55362a955.png)

![image](https://user-images.githubusercontent.com/19325380/76518336-e308cc80-6499-11ea-98b7-0f5bb910c920.png)

**Comment by evernat** [comment]
Do you know how many different "requests" (or errors) you have added per 60 seconds?
What is the use case for this issue?

**Comment by mymilkbottles** [comment]
> Do you know how many different "requests" (or errors) you have added per 60 seconds?
> What is the use case for this issue?

This is in trading scenario and High concurrent application，it will Insert a large number of transaction flow in a short time，so 60 seconds will insert more than 10000 transaction flow，every failed transaction flow put a CounterRequest  in requests（net.bull.javamelody.internal.model.Counter#requests） ，so it will cost large memory

**Comment by evernat** [comment]
First, in the junit test you have given, an OOM is produced with a heap as low as Xmx30m after more than 10000 transaction flow. So it seems like there is no major issue even with Xmx30m.
And every 60 seconds by default, any issue disappear with the Collector.
Second, you may suppress any issue you have:
- either configure the resolution with a parameter (for example -Djavamelody.resolution-seconds=30 instead of 60)
- or do not log so many thousands warnings/errors: use something like a circuit breaker
- or increase your heap to something more than Xmx30m
Then,
- I am aware of heaps with a size of hundreds of GB or in TB, so 30MB of used memory in this corner case seems more like a raspberry experiment than an issue.
- You may think that you have an issue, but that's never, never a reason to introduce a regression for everyone by adding a slow operation in a method which should be fast while running transactions.
- That's not a reason either to remove code which was needed to limit used memory for some aggregations.
So closing as not an issue. Thank you anyway for your interest.

**Comment by evernat** [comment]
I forgot: another way to suppress any issue is by disabling the "error" Counter, with the parameter displayed-counters (-Djavamelody.displayed-counters).

**Comment by mymilkbottles** [comment]
> First, in the junit test you have given, an OOM is produced with a heap as low as Xmx30m after more than 10000 transaction flow. So it seems like there is no major issue even with Xmx30m.
> And every 60 seconds by default, any issue disappear with the Collector.
> Second, you may suppress any issue you have:
> 
> * either configure the resolution with a parameter (for example -Djavamelody.resolution-seconds=30 instead of 60)
> * or do not log so many thousands warnings/errors: use something like a circuit breaker
> * or increase your heap to something more than Xmx30m
> 
> Then,
> 
> * I am aware of heaps with a size of hundreds of GB or in TB, so 30MB of used memory in this corner case seems more like a raspberry experiment than an issue.
> * You may think that you have an issue, but that's never, never a reason to introduce a regression for everyone by adding a slow operation in a method which should be fast while running transactions.
> * That's not a reason either to remove code which was needed to limit used memory for some aggregations.
>   So closing as not an issue. Thank you anyway for your interest.

ok, thank you for your patiently answer.
