### ISSUE TITLE
unknown hostname in awscloudwatch

### ISSUE THREAD

**Issue by sunil1979** [javamelody/javamelody#904]
Hi,

I have configured javamelody to send metrics to aws cloudwatch. The metrics are sent to cloudwatch from ec2 instance. My webapp is running on tomcat and aws credentials are set through setenv.sh file. The hostname in the metrics is set to "unknown". Am i missing any configuration? below is my configuration of javamelody in web.xml

	<filter>
		<filter-name>javamelody</filter-name>
		<filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
		<async-supported>true</async-supported>
		<init-param>
			<param-name>cloudwatch-namespace</param-name>
			<param-value>fairbroker/api</param-value>
		</init-param>
	</filter>
	<filter-mapping>
		<filter-name>javamelody</filter-name>
		<url-pattern>/api/*</url-pattern>
		<dispatcher>REQUEST</dispatcher>
		<dispatcher>ASYNC</dispatcher>
	</filter-mapping>
	<filter-mapping>
		<filter-name>javamelody</filter-name>
		<url-pattern>/monitoring</url-pattern>
	</filter-mapping>
	<listener>
		<listener-class>net.bull.javamelody.SessionListener</listener-class>
	</listener>

**Comment by evernat** [comment]
It is displayed "unknown" in Cloudwatch because the hostname is unknown in javamelody and that is absolutely not related to Cloudwatch.
It is unknown in javamelody because `InetAddress.getLocalHost().getHostName()` throws `UnknownHostException`.

The problem can be fixed by adding the hostname of your server in your `/etc/hosts` file.
For example, get your hostname by running the `hostname` command.
Then you may add your hostname at the end of the lines starting with `127.0.0.1   localhost` or with `::1         localhost` for example.
