### ISSUE TITLE
Sessions attributes are not updated when Spring Session is used

### ISSUE THREAD

**Issue by Monichev** [javamelody/javamelody#906]
SessionListener stores initial versions of all HttpSessions it gets and wants them to be updated by someone else (i.e. Tomcat) from outside.

In case of Spring Session (with Redis Repository) HttpSession is not a singleton. And Spring doesn't update the firstly created HttpSession object. So any attributes changed later are not visible for JavaMelody.

**Comment by evernat** [comment]
When using Spring-session with Redis, the state of an http session from an http request is not good anymore a few seconds or a few minutes later, because its state is not in the same instance and is not in sync with the http session from another http request and/or from an HttpSessionListener. So the session attributes in the javamelody report for the detail of a session are wrong (not updated).
I think that this is an issue in Spring session, which does not respect the servlet api spec in my opinion. So this issue in javamelody is probably invalid, like #826.

Then the PR #907 is a bit complex and it needs to implement and set a `SessionProvider` in the webapp.
If you wish to workaround this issue in javamelody, I think that the commit 9c0c553 in the [spring-session-redis branch](https://github.com/javamelody/javamelody/tree/spring-session-redis) would have the same effect to fix the issue. This commit [attached for reference](https://github.com/javamelody/javamelody/files/4484236/9c0c553a9b7dfb8f5acee91e8472dc9827fd4463.txt) would probably not be merged, since this issue is probably invalid in javamelody.
What do you think?

**Comment by Monichev** [comment]
Sure, anyway this solution is not elegant because of static nature of SessionListener.
I wish it could be customizable so I would be able to made these changes without adding them to the JavaMelody sources.

**Comment by evernat** [comment]
ok, thanks for the issue.
Closing as invalid in javamelody as said above.
