### ISSUE TITLE
jrobin version

### ISSUE THREAD

**Issue by clauswit** [javamelody/javamelody#908]
Hi,
is there a reason jrobin version 1.5.9 is used - and not 1.5.9.1 or maybe a newer version like 1.5.14 (which is also outdated)?
https://sourceforge.net/projects/jrobin/files/jrobin/

What is the difference between https://mvnrepository.com/artifact/org.jrobin/jrobin/1.5.9 and https://sourceforge.net/projects/jrobin/files/jrobin/1.5.9/

Greetings
Claus

**Comment by evernat** [comment]
> What is the difference between https://mvnrepository.com/artifact/org.jrobin/jrobin/1.5.9 and https://sourceforge.net/projects/jrobin/files/jrobin/1.5.9/

https://mvnrepository.com/ is not a repository and it does not contain any artifact. It is just a duplicate of Maven Central (https://search.maven.org) and other repositories, to display ads and I suppose to earn money, for some guy named frodriguez which is probably rich now.
The question to ask is:

> What is the difference between https://search.maven.org/artifact/org.jrobin/jrobin/1.5.9/jar (https://repo1.maven.org/maven2/org/jrobin/jrobin/1.5.9/) and https://sourceforge.net/projects/jrobin/files/jrobin/1.5.9/ (version 1.5.9.1) ?

In fact, Maven Central (https://repo1.maven.org/maven2/org/jrobin/jrobin/1.5.9/) contains the same as OpenNMS repo (http://repo.opennms.org/maven2/org/jrobin/jrobin/1.5.9/). And jrobin-1.5.9.1.jar is present in sourceforge.net, but it is not present in OpenNMS Maven repo. (OpenNMS is the current maintainer of JRobin.)
The difference between jrobin-1.5.9.jar from Maven Central and jrobin-1.5.9.1.jar from sourceforge seems to be that jrobin-1.5.9.jar and other jar files from OpenNMS contains 2 Dejavu ttf files. (Those ttf files use a free license, https://dejavu-fonts.github.io/, similar to the Open Font license.)

> is there a reason jrobin version 1.5.9 is used - and not 1.5.9.1 or maybe a newer version like 1.5.14 (which is also outdated)?
https://sourceforge.net/projects/jrobin/files/jrobin/

The OpenNMS repo (http://repo.opennms.org/maven2/org/jrobin/jrobin/) also contains 1.6.0.
The reason to use jrobin 1.5.9 and not 1.5.14 or 1.6.0 is that 1.5.9 is the only version available in Maven central (https://search.maven.org/artifact/org.jrobin/jrobin/1.5.9/jar) and we can't force a user to add an OpenNMS repo in all their Maven configurations and their client's Maven configurations, in order to use our tool. And there is also a rule that artifacts in Maven central must not depend on an artifact in any (not reliable) repository outside of Maven central.
Otherwise, javamelody is compatible with jrobin 1.6.0 for what I have seen, but javamelody will always use its own RrdNioBackendFactory instead of jrobin's one, to fix Java 9+ compatibility and to manage the jrobin's sync thread.

Is it ok for you?

**Comment by clauswit** [comment]
Yes, Thank you very much!
