### ISSUE TITLE
getting error : Couldn't retrieve job because the BLOB couldn't be deserialized

### ISSUE THREAD

**Issue by vinothank95** [javamelody/javamelody#917]
Hi,
using 1.83.0 JAR For my project. everthing is fine but getting below exception in logs....

- [javamelody] [net.bull.javamelody.internal.common.Log4JLogger.debug(Log4JLogger.java:59)] DEBUG org.quartz.JobPersistenceException: Couldn't retrieve job because the BLOB couldn't be deserialized: com.vit.vi.hb.Customer; local class incompatible: stream classdesc serialVersionUID = -247880084599301324, local class serialVersionUID = -740369902611687750 [See nested exception: java.io.InvalidClassException: com.vit.vi.hb.Customer; local class incompatible: stream classdesc serialVersionUID = -247880084599301324, local class serialVersionUID = -740369902611687750]
- org.quartz.JobPersistenceException: Couldn't retrieve job because the BLOB couldn't be deserialized: com.vit.vi.hb.Customer; local class incompatible: stream classdesc serialVersionUID = -247880084599301324, local class serialVersionUID = -740369902611687750 [See nested exception: java.io.InvalidClassException: com.vit.vi.hb.Customer; local class incompatible: stream classdesc serialVersionUID = -247880084599301324, local class serialVersionUID = -740369902611687750]
  - at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1397)
    - at org.quartz.impl.jdbcjobstore.JobStoreSupport$9.execute(JobStoreSupport.java:1382)
    - at org.quartz.impl.jdbcjobstore.JobStoreCMT.executeInLock(JobStoreCMT.java:245)
    - at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeWithoutLock(JobStoreSupport.java:3785)
    - at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1379)
    - at org.quartz.core.QuartzScheduler.getJobDetail(QuartzScheduler.java:1487)
    - at org.quartz.impl.StdScheduler.getJobDetail(StdScheduler.java:498)
    - at net.bull.javamelody.internal.model.Quartz2Adapter.getAllJobsOfScheduler(Quartz2Adapter.java:154)
    - at net.bull.javamelody.internal.model.JobInformations.buildJobInformationsList(JobInformations.java:163)
    - at net.bull.javamelody.internal.model.JavaInformations.<init>(JavaInformations.java:205)
    - at net.bull.javamelody.internal.model.UpdateChecker.getAnonymousData(UpdateChecker.java:136)
    - at net.bull.javamelody.internal.model.UpdateChecker.checkForUpdate(UpdateChecker.java:109)
    - at net.bull.javamelody.internal.model.UpdateChecker$1.run(UpdateChecker.java:83)
    - at java.util.TimerThread.mainLoop(Timer.java:555)
    - at java.util.TimerThread.run(Timer.java:505)
- Caused by: java.io.InvalidClassException: com.vit.vi.hb.Customer; local class incompatible: stream classdesc serialVersionUID = -247880084599301324, local class serialVersionUID = -740369902611687750

**Comment by evernat** [comment]
It seems that there is at least one job in your database that is invalid. It is invalid because it references the `com.vit.vi.hb.Customer` class and that the serialVersionUID value written in this Customer class has changed between when the job was added in the database and now when you are running the application.

javamelody is not related to this issue, so closing the issue as invalid here. javamelody just logs at debug level the invalid job issue when you display the monitoring page. Depending on your app, that issue may be transient or not and it may happen or not outside of dev/QA environments.

Anyway, to fix the issue in your app, you may either:
- clean-up the jobs in your database when you change the classes referenced by the job details
- or never change the serialVersionUID value in your Customer class (initial value was -247880084599301324) and deal if necessary with the missing field values in the Customer instances of the jobs which are still in the database.

Otherwise, you can ignore that logs if you don't want to know more about your invalid jobs.
