### ISSUE TITLE
Javamelody displays database URL by default (may contain credentials)

### ISSUE THREAD

**Issue by dtipaldo** [javamelody/javamelody#920]
Inside the System Details Section, Database connection strings (credentials) are displayed in clear text, this could be seen as a security vulnerability.

**As a** Javamelody user
**I** do not want to see the username and password to my application's database
**So that** I am not exposed to secrets that belong to my PasS

**Comment by evernat** [comment]
As far as I know, javamelody never reads or displays passwords to your application's database. Special care was put for this, since the beginning of javamelody, for example [in MBeans](https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/internal/model/MBeans.java#L210).
Can you send more information in private to me (evernat at free.fr) ? Without secret data of course. I miss some information to see the relation between this case and the PR on the threads.

**Comment by dtipaldo** [comment]
I provided you some more information privately. In addition, I've renamed the title of the issue to better clarify what is happening. The database URL is where credentials may be exposed. In the case where a PaaS provides the database URL, a developer may unknowingly be exposed to platform secrets. The PR provides a way to hide a few server details field, the Database URL included.

**Comment by evernat** [comment]
Using password in a jdbc URL like in `jdbc:mysql://localhost:3306/mydb?user=myuser&password=mypassword` is a bad practice which is never used as far as I know. There is plenty of docs on the Internet which show how to do otherwise.

It seems that you are using a DataSource, probably a Spring or Spring-boot DataSource. You can see how to configure a Spring-boot DataSource at:
https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-connect-to-production-database
Or you can see how to configure a Spring DataSource using xml at:
https://docs.spring.io/spring/docs/current/spring-framework-reference/data-access.html#transaction-strategies
or at:
https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/core.html#beans-value-element
Otherwise you can see how to configure a DataSource from JNDI in Tomcat 9 at:
https://tomcat.apache.org/tomcat-9.0-doc/jndi-datasource-examples-howto.html#MySQL_DBCP_2_Example
or in Tomcat 7 at:
https://tomcat.apache.org/tomcat-7.0-doc/jndi-datasource-examples-howto.html#MySQL_DBCP_1.x_Example

By the way, there is no reason to disable threads and jobs and caches and hserrpid informations. So closing the PR #921.
