### ISSUE TITLE
How to get data from JavaMelody (JIRA/Bitbucket/Confluence) add-on

### ISSUE THREAD

**Issue by gawlik** [javamelody/javamelody#922]
Hi,

Is any option to get JavaMelody in format like: json, yaml or XML?
https://<domain>/monitoring?part=graph&graph=activeThreads&format=xml
Additing format doesn't work.

Addictionaly, we would like to pass information to splunk but dump doesn't work:
rrdtool dump usedSwapSpaceSize_2.rrd > usedSwapSpaceSize_2.xml
ERROR: 'usedSwapSpaceSize_2.rrd' is not an RRD file

rrdtool --version
RRDtool 1.4.8 

Thank you in advance for help!

Regards

Michal

**Comment by evernat** [comment]
For the URLs, first you need to use version 1.83.0.
Then you need to use the right URLs, for example:
```
http://.../monitoring?graph=activeThreads&period=jour&format=xml
http://.../monitoring?graph=activeThreads&period=jour&format=txt
http://.../monitoring?graph=activeThreads&period=tout&format=xml
http://.../monitoring?graph=activeThreads&period=tout&format=txt
```
When the period parameter is `tout`, the dump contains all the values, for all the periods, like [rrddump](https://oss.oetiker.ch/rrdtool/doc/rrddump.en.html). Otherwise, the dump contains the average values in the highest resolution available for the choosen period, like [rrdfetch](https://oss.oetiker.ch/rrdtool/doc/rrdfetch.en.html).
Links below zoomed graphics are provided for this.
See doc at: https://github.com/javamelody/javamelody/wiki/ExternalAPI#dump-graph-as-xml-or-txt

If you want to use the command line, I suppose that you may use `curl` and the URLs above with authentication.
Otherwise, the rrd format of javamelody is not exactly the same as the one from rrdtool. But you can use jrobin-1.5.9.jar file and Java 8 (not Java 9+).
See doc at: https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#format-of-rrd-files

**Comment by evernat** [comment]
Above is for graph data, you may also get other data such as statistics, for example:
```
http://.../monitoring?periord=jour&format=xml
http://.../monitoring?periord=jour&format=json
http://.../monitoring?periord=jour&format=gson
http://.../monitoring?periord=tout&format=xml
http://.../monitoring?periord=tout&format=json
http://.../monitoring?periord=tout&format=gson
```
It works because xstream and guava are included in JIRA for example.
see doc: https://github.com/javamelody/javamelody/wiki/ExternalAPI#xml
