### ISSUE TITLE
In progress queries not found in the application server access log

### ISSUE THREAD

**Issue by adrianboangiu** [javamelody/javamelody#928]
We use JavaMelody to monitor an application deployed under Wildfly 10.1 Final.
We have noticed in the section of in progress http requests some ghost requests. They are displayed forever in JavaMelody with their response time steadily increasing but we cannot find them in the application server’s access log.
The image below shows 3 requests in progress.
<img width="892" alt="ghost1" src="https://user-images.githubusercontent.com/28983495/86485732-c4d12000-bd59-11ea-807e-deeb63e4c159.png">

The following image shows the access log of the application server filtered to find the 1st in progress query using a log treatment application (using the token b3gt5lrhv). As a result, we have 2 POST queries but not the GET query shown by JavaMelody.
<img width="1021" alt="ghost2" src="https://user-images.githubusercontent.com/28983495/86485826-08c42500-bd5a-11ea-8be2-0f92a2ce27c8.png">
The following image shows the access log of the application server filtered to find the 2nd in progress query (using the token kp6qyrl). As a result, again we have 2 POST queries but not the GET query shown by JavaMelody.
<img width="998" alt="ghost3" src="https://user-images.githubusercontent.com/28983495/86485838-124d8d00-bd5a-11ea-9182-9107035865b9.png">
The following image shows the access log of the application server filtered to find the 3rd in progress query (using the token -1cdfrxstm). As a result, we have several queries having the variable _afPfm (a state variable used by Oracle ADF-the framework used to develop the application) equal to the searched token but none equal with -1cdfrxstmo (the exact value of the variable used in the 3rd in progress query).
<img width="1014" alt="ghost4" src="https://user-images.githubusercontent.com/28983495/86485817-fe099000-bd59-11ea-82ea-ba798f30a341.png">
Any idea why this happens?

**Comment by evernat** [comment]
There may be an explanation: javamelody is right and the requests are still current 😄
These requests may be long and not yet ended. So there are not yet written in acces log because they will be written in access log when they end.
The requests may be long because they may be waiting for something which may never happen, for example a lock in the webapp or in the server or in some database.
To see what the code for the requests is doing, you can see the stack-trace of the threads when your mouse is over the names of the threads in the current requests report of javamelody. You can also see the JVM states of the threads in the list of threads below the current requests, but stack-traces are more important.
Try to validate that the stack-traces of the threads are indeed for the current http requests.
Check also if the graphs of active threads (and active jdbc connections, opened jdbc connections) shows an almost flat level at 3 since hours.
Is it ok for you?

Perhaphs there are other possible explanations, but I don't know them at the moment.

**Comment by adrianboangiu** [comment]
Thank you. The first two threads are just waiting (they are in the method sun.misc.Unsafe.park() which is basically Thread.wait). Most of the threads are in this situation. Seems strange since they do not consume CPU so I don't know what they are waiting for.
The third example seems to be reading something from the database. This again is very strange since we have timeout limits for the cases where the connection is broken. Could it be possible to have for the in progress requests the analysis of the sql statements (like we have it for normal finished requests)? Like this we could see where the current request is spending its time (if it is the sql prt that is working).
Best regards

**Comment by evernat** [comment]
The first two threads are probably waiting for something to happen in java. That something waiting to happen may be related to the end of the third thread.
It seems that your timeouts are not used in this case. Indeed the connection does not seem broken. It is just long to finish. It seems that you don't have configured javamelody to monitor sql requests, otherwise knowing which sql requests are long may have been interesting. So at the moment, you may find which sql request(s) are currently executing using the stack-trace of the thread and the code for each line of the stack-trace. Otherwise you may ask to your database, with javamelody or by yourself (`select * from pg_stat_activity` for example), what are the current sql requests which are executing.

**Comment by evernat** [comment]
any news?

**Comment by evernat** [comment]
no response so closing.
