### ISSUE TITLE
Requests reporting different average and maximum than the graphical representation

### ISSUE THREAD

**Issue by adrianboangiu** [javamelody/javamelody#929]
We have requests that reports huge average and maximum response times. However, when we display the details other figures are reported. Almost all the requests of our application are in this situation. Take the example below.
![max1](https://user-images.githubusercontent.com/28983495/86575054-f6730280-bf76-11ea-9b9b-913f4d0479a5.jpg)
The request /20185396.xhtml POST is announced with 120227 ms average and 819959 ms max response time.
When we display the details, we still see those figures in the table but the graphic is reporting some different figures: 639 ms in average and 900 ms in max.
![max2](https://user-images.githubusercontent.com/28983495/86575657-ead40b80-bf77-11ea-986c-71626fd45278.jpg)
Is our interpretation of the graphic correct and in that case the figures are wrong? Or the figures are good and our interpretation is not correct?
Thank you

**Comment by evernat** [comment]
The statistics are always correct. For (RRD) graph, mean/max are not meaningful here.

The statistics of requests display mean, max and standard-deviation since midnight. While the mean and max at the bottom of the graph are from values in the graph for all the range in the graph. (In this case, the graph is displayed almost since midnight, so it's not a good reason here.)
Then in this case, we can see in the graph that there are very few values. The (RRD) graph records one value per minute and there are no values for hours then 2 or 3 values for a few minutes. The [xff (x files factor)](https://oss.oetiker.ch/rrdtool/doc/rrdcreate.en.html) exclude some values when there are not enough values to have meanigful aggregation.
What is sure is that the statistics of requests are exact, since midgnight, because there is no exclusion (but the current requests are not in the statistics yet, because the durations are not yet known).
