### ISSUE TITLE
For heap histogram, Openjdk:8-jdk-alpine is not supported.

### ISSUE THREAD

**Issue by harvies** [javamelody/javamelody#936]
bash-4.4# java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

net.bull.javamelody.internal.model.VirtualMachine#isSupported  return false.

**Comment by evernat** [comment]
This is an issue for the heap histogram feature: the link to display heap histogram is removed from the monitoring UI.

The goal of the isSupported() method using the "java.vendor" system property was to support JDK from Sun, Oracle, Apple and also JRockit from BEA and so to exclude J9 from IBM because of incompatibility.
Years later, the cause of the issue is that AdoptOpenJDK, Amazon, Azul, SAP have now put their own names in the "java.vendor" system property.
I think that we should change this method so that if `System.getProperty("java.vm.name").contains("OpenJDK")`, then the JVM is also supported for heap histogram.

**Comment by harvies** [comment]
I agree.

**Comment by evernat** [comment]
Fixed by  ddf10cc and ready for the next release (1.86).
A snapshot build is available at : http://javamelody.org/downloads/javamelody-core-1.86.0-SNAPSHOT.jar

**Comment by vanta** [comment]
@evernat when we can expect the next version to be released? This is a pretty crucial feature for us.

**Comment by evernat** [comment]
@vanta javamelody 1.86.0 is released just now
Release notes: https://github.com/javamelody/javamelody/wiki/ReleaseNotes#1860
