### ISSUE TITLE
Spring Boot 2 and Quartz monitoring

### ISSUE THREAD

**Issue by okianl** [javamelody/javamelody#940]
I was able to get Spring Boot 2.3.3. app with Java Melody Spring Boot Starter 1.85.0 and Quartz 2.3.2 in JDBC mode (managed by Spring).
I also used this setting **javamelody.init-parameters.quartz-default-listener-disabled=true** to disable the default quartz instance.(I checked that in threads and it's working)

However, when I look at the job stats, I don't see any hits (the jobs are running every 2 seconds) and the SQL stats(the entire columns) are missing also for the jobs.

Any idea what could be wrong? You think it could be because Javamelody get initialized before Quartz autoconfiguration?

**Comment by evernat** [comment]
Sorry for the delay.
There are 2 issues for this to work in Spring Boot:
1. First, we need to set `exposeSchedulerInRepository=true` in Spring's SchedulerFactoryBean as said in the user's guide: https://github.com/javamelody/javamelody/wiki/UserGuide#13-batch-jobs-if-quartz
2. Then, JavaMelody was indeed initialized before Quartz autoconfiguration in Spring Boot, so JavaMelody did not see the Spring's Quartz scheduler to add a Quartz JobListener, before the scheduler exists.

Both are fixed by 6b87db6 and ready for the next release (1.86) soon. You don't need to do anything except use the 1.86 release.

And yes, you can use `javamelody.init-parameters.quartz-default-listener-disabled=true` to not start the default Quartz instance and to start only the Spring's Quartz instance. But that is not related to this particular issue.

**Comment by okianl** [comment]
It works great as described.
