### ISSUE TITLE
Tomcat 7, jdbc connections aren't monitored

### ISSUE THREAD

**Issue by massimosala** [javamelody/javamelody#941]
Hi
We have tomcat 7.0.42.
I read the [manual](https://github.com/javamelody/javamelody/wiki/UserGuide#7-jdbc)
I don't understand if our configuration is correct for javamelody "auto-discovery":

/home/folium/folium-prod/apache-tomcat-7.0.42/conf/context.xml
```
      <Resource name="jdbc/folium"
      url="jdbc:postgresql://postgresqldb:5432/folium"

```

/home/folium/folium-prod/local-conf.xml
```
      <data-service jndi-enabled="true" jndi-position="java:/comp/env/jdbc/folium" />
```

/home/folium/folium-prod/webapp/WEB-INF/enti/ATSBergamo/data-service-conf.xml
```
         <jndi-position>java:/comp/env/jdbc/folium</jndi-position>
```

Questions:
1) context.xml : is it correct url="jdbc:postgresql://..." or is it better url="jdbc://..." ?

2) local-conf.xml : is it correct jndi-position="java:/comp/..." or is it better jndi-position="java:comp/..."

3) should I add this java parameter ?
    -Djavamelody.datasources=java:comp/env/jdbc/folium

Best regards, Sala

**Comment by evernat** [comment]
First, `<Resource name="jdbc/folium" ...>` is correct for auto-discovery by javamelody because it starts with "jdbc/".
Then for your questions:
1. I usually see url="jdbc:postgresql://...". But it does not make any difference for javamelody, as long as it works to connect to your database from your webapp
2. For the JNDI lookup of the datasource like `new InitialContext().lookup("java:comp/env/jdbc/folium")`, I usually see "java:comp/env/jdbc/...". But I do not think that it makes any difference for javamelody.
3. Since javamelody auto-discovers datasources for JNDI URLs like "java:comp/env/jdbc/...", it is not necessary. But it does not make any difference here to override auto-discovery with `-Djavamelody.datasources=java:comp/env/jdbc/folium`.

I suggest to look at the debugging logs at the bottom of the monitoring page after starting and to copy it here. It says what datasources is auto-discovered and what it does with it.

And since you have `<data-service jndi-enabled="true" jndi-position="java:/comp/env/jdbc/folium" />` in a `local-conf.xml` file, perhaps you have a servlet listener that is getting and caching the datasource from JNDI before the initialization of javamelody in the javamelody SessionListener. In that case, it may help that the following listener is written in your `WEB-INF/web.xml` file before your servlet listener :
```xml
	<listener>
		<listener-class>net.bull.javamelody.SessionListener</listener-class>
	</listener>
```
Let us know how it goes.

**Comment by evernat** [comment]
Of course I suppose that there were no jdbc connections in the graphs and no sql requests in the statistics.

**Comment by massimosala** [comment]
Hi @evernat 

Many thanks for your answers.

Please see the logs. The server is restarte every morning at 3:30 AM.

`Mon Oct 05 03:31:23 CEST 2020     DEBUG     datasources found in JNDI: []
`

Does it mean autodiscovery isn't working ?

[javamelody_debugging_logs.txt](https://github.com/javamelody/javamelody/files/5325893/javamelody_debugging_logs.txt)

**Comment by massimosala** [comment]
![image](https://user-images.githubusercontent.com/20907433/95058391-c2cf8200-06f7-11eb-90ff-70926f22f0a7.png)

**Comment by evernat** [comment]
OK, you have put the javamelody-core jar file and probably the jrobin jar file in the Tomcat lib directory.
But you are supposed instead to put the javamelody-core jar file and the jrobin-1.5.9 jar file in the WEB-INF/lib directory of your webapp, as said in the user's guide: https://github.com/javamelody/javamelody/wiki/UserGuide#javamelody-setup

That said, if you insist to not follow the javamelody user's guide and to keep the javamelody-core jar file in the Tomcat lib directory, it may help if you remove every webapp from the Tomcat webapps directory (docs, host-manager, ...), except your webapp. Perhaps it will workaround the issue but it will not be officially supported, because you are supposed to do as said in the user's guide: https://github.com/javamelody/javamelody/wiki/UserGuide#javamelody-setup

Is it OK for you ?

**Comment by massimosala** [comment]
Hi @evernat 

I did a mistake about the location of the jar files. I fixed this error.
Please see the new logs.

![image](https://user-images.githubusercontent.com/20907433/95442215-653b6f80-095b-11eb-9c2f-41b3e367ce97.png)
[javamelody_debugging_logs.txt](https://github.com/javamelody/javamelody/files/5346801/javamelody_debugging_logs.txt)

**Comment by massimosala** [comment]
I don't understand : the JDBC connections and SQL info (hits/minute, average time, errors) aren't visualized.

Instead SYSTEM INFORMATION : DATABASE works:
![image](https://user-images.githubusercontent.com/20907433/95450307-61611a80-0966-11eb-9cd9-929b160a70a3.png)

**Comment by massimosala** [comment]
> And since you have `<data-service jndi-enabled="true" jndi-position="java:/comp/env/jdbc/folium" />` in a `local-conf.xml` file, perhaps you have a servlet listener that is getting and caching the datasource from JNDI before the initialization of javamelody in the javamelody SessionListener. In that case, it may help that the following listener is written in your `WEB-INF/web.xml` file before your servlet listener :
> 
> ```
> 	<listener>
> 		<listener-class>net.bull.javamelody.SessionListener</listener-class>
> 	</listener>
> ```


Yes, we have this file
`/home/folium/folium-prod/webapp/WEB-INF/web.xml
`
but it doesn't list any listener, so I don't know if / how to modify it.

**Comment by massimosala** [comment]
I added the listener to the start of the web.xml, as suggested, and now the reports are OK.
Many thanks for your support.
