### ISSUE TITLE
JOBS, Italian localization is incorrect

### ISSUE THREAD

**Issue by massimosala** [javamelody/javamelody#943]
![image](https://user-images.githubusercontent.com/20907433/95442542-cebb7e00-095b-11eb-8b41-4eb9c29817d1.png)

It seems to me the 7th column header is about the previous execution, in Italian: "Esecuzione precedente".
Now it is "Eccezione", meaning exception. I think it is wrong.

BTW, compliments for the excellent work.

**Comment by evernat** [comment]
You are right.
Thank you.
It's fixed by 04d89e2 and ready for the next release (1.86).

Note that to contribute in Italian or in another language, you can join the translation project for javamelody at https://poeditor.com/join/project/QIaCp4bThS.
For example, some Italian translations are missing for:
- Heap dump {0} uploaded successfully to S3. _(that's when a parameter is configured for S3)_
- Waiting in build queue (s) _(s is for seconds)_
- Add an aggregation
- Name of aggregation to monitor
- Choice of applications to aggregate
- Usable disk space
- Some nodes are unavailable
