### ISSUE TITLE
Monitoring not started on reboot without visiting monitoring page once?

### ISSUE THREAD

**Issue by eric-gagnon** [javamelody/javamelody#954]
Hello,

A coworker stopped a VM this morning to install more memory and I noticed a big empty gap in monitoring graph (memory / cpu) (second gap at right is an attempt to reproduce the issue, restart of Wildfly and waiting before going in javamelody monitoring page).

![image](https://user-images.githubusercontent.com/21067311/97353209-1e5ddd00-186a-11eb-87b6-c63a93fbe676.png)

I have verified in the logs : Wildfly and our Spring boot application where started.

Is this a known behavior of JavaMelody, some kind of lazy start? That you would need to access the app a first time to get the monitoring going?

I'm using the simple embedding in a Spring boot app and simple filter / filter-mapping and listener as provided in integration samples.

I will investigate on my side and also dig in the sources but will gladly take any help. I have done a quick search but maybe I'm not using the right keywords.

Thanks for the wonderfull project!

Eric

**Comment by evernat** [comment]
Most javamelody features are initialized by its MonitoringFilter (in the servlet filter init method).
And it seems to me that in some versions of Undertow, WildFly and JBoss EAP, servlet filters are initialized lazily, on the first request.

Said otherwise, yes there are holes in the graphs when using WildFly, after restart when there is absolutely no user, but at the same time there is no user so not much to monitor. So it could be seen as the desired behavior of the lazy init enabled by default in WildFly: no request, no monitoring. (In France, we say for a long time: pas de bras, pas de chocolat 😄)
So perhaps there is no issue, what do you think?

Otherwise there is at least a workaround: `eager-filter-initialization="true"` in the servlet container config:
```xml
<subsystem xmlns="urn:jboss:domain:undertow:3.1">
    <servlet-container name="default" eager-filter-initialization="true">
        <jsp-config/>
        <websockets/>
    </servlet-container>
</subsystem>
```
See https://issues.redhat.com/browse/WFLY-3028

**Comment by eric-gagnon** [comment]
Je ne connaissais pas l'expression!

It make sense!  The app I'm working with is deployed on a secondary server with a different profile to process heavy jobs, so there is no request getting back.

Thanks for pointing me to a possible solution, I will give it a look. 

Salutations de Montréal!

Eric
