### ISSUE TITLE
Question about Mean allocated Kb  column under Spring Stats.

### ISSUE THREAD

**Issue by virtualdogbert** [javamelody/javamelody#968]
In a  Grails app I'm looking at melody under Spring Stats(details). I'm looking at one call to a service under the Mean allocated Kb column and it's 269,432 which would seem to mean that call is taking 256MB... which doesn't make sense to me because that call returns an empty list. The reason I'm looking into this is that on production we have a method that has a Mean allocated Kb  of 71,000,000 which would indicate 71GB, which I don't think is possible with a 5 GB heap. What does Mean allocated Kb actually mean or could it be off by a few orders of magnitude?

**Comment by evernat** [comment]
> I'm looking at one call to a service under the Mean allocated Kb column and it's 269,432 which would seem to mean that call is taking 256MB

Yes, the Mean allocated Kb means the allocated memory between the start and the end of the method. Note that it is a mean (sum divided by the number of executions) for all executions on the period. When there are more than one execution on the period, it is not the value for a particular execution.

> The reason I'm looking into this is that on production we have a method that has a Mean allocated Kb of 71,000,000 which would indicate 71GB, which I don't think is possible with a 5 GB heap.

It's possible to have 71 GB allocated in a method with a 5 GB heap, because that memory can be allocated and then deallocated as execution progresses.

Large allocated memory values are often with arrays of bytes. For a bad example in java:
```java
	void listNotEmptyFiles(File directory) throws IOException {
	  for (File file : directory.listFiles()) {
	    byte[] content = read(file);
	    if (content.length > 0) {
	      System.out.println(file);
	    }
	  }
	}

	byte[] read(File file) throws IOException {
	  ByteArrayOutputStream out = new ByteArrayOutputStream();
	  try (FileInputStream in = new FileInputStream(file)) {
	    pump(in, out);
	  }
	  return out.toByteArray();
	}
	
	void pump(InputStream in, OutputStream out) throws IOException {
	    while (true) {
	      byte[] buffer = new byte[4096];
	      int read = in.read(buffer);
	      if (read == -1) {
	         break;
	      }
	      out.write(buffer, 0, read);
	    }			
	}
```
Using the `listNotEmptyFiles` method, to list not empty files in a directory, would allocate more memory than 3 times the size of files because of different bad practices. The allocated memory in this method increases fast and probably more than the heap size.

Those bad practices are evident for this small example, but they may not be evident with a lot of method calls, of libraries and of beginner developers you may be working with.
